LifeSG/web-frontend-engine

- src/components/fields/index.ts
- src/components/fields/select/index.ts
- src/components/fields/select/select.tsx
- src/components/fields/select/types.ts
- src/components/fields/submit-button/index.ts
- src/components/fields/submit-button/submit-button.tsx
- src/components/fields/submit-button/types.ts
- src/components/fields/textarea/textarea.tsx
- src/components/fields/textarea/types.ts
- src/components/fields/textfield/index.ts
- src/components/fields/textfield/textfield.tsx
- src/components/fields/textfield/types.ts
- src/components/frontend-engine/frontend-engine.tsx
- src/components/frontend-engine/types.ts
- src/stories/3-fields/select/select.stories.tsx
- src/stories/3-fields/submit-button/submit-button.stories.tsx
- src/stories/3-fields/textarea/textarea.stories.tsx
- src/stories/3-fields/textfield/textfield.stories.tsx
- src/stories/common.ts
- src/utils/hooks/use-validation-schema.ts
- Created individual components
- Setup storybook
- Ready to merge
> Create submit button and textfield component

- package-lock.json
- package.json
- rollup.config.js
- src/components/fields/date-input/date-input.tsx
- src/components/fields/date-input/index.ts
- src/components/fields/date-input/types.ts
- src/components/fields/index.ts
- src/components/fields/wrapper/index.ts
- src/components/fields/wrapper/types.ts
- src/components/fields/wrapper/wrapper.tsx
- src/components/frontend-engine/frontend-engine.tsx
- src/components/frontend-engine/types.ts
- src/stories/1-intro/1-intro.stories.mdx
- src/stories/2-frontend-engine/validation.stories.tsx
- src/stories/3-fields/date-input/date-input.stories.tsx
- src/stories/3-fields/wrapper/wrapper.stories.tsx
- Created wrapper field
- Moved logic to render individual field to wrapper component to avoid repeating codes
- Created date input field
- Installed js-joda packages to handle date formats
> Create wrapper and date input fields

- src/components/fields/checkbox-group/checkbox-group.styles.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/date-input/date-input.tsx
- src/components/fields/index.ts
- src/components/fields/radio-button/index.ts
- src/components/fields/radio-button/radio-button.styles.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/radio-button/types.ts
- src/components/fields/time-picker/index.ts
- src/components/fields/time-picker/time-picker.tsx
- src/components/fields/time-picker/types.ts
- src/components/frontend-engine/types.ts
- src/components/shared/error-messages.ts
- src/stories/3-fields/date-input/date-input.stories.tsx
- src/stories/3-fields/radio-button/radio-button.stories.tsx
- src/stories/3-fields/time-picker/time-picker.stories.tsx
- src/utils/date-helper.ts
- src/utils/index.ts
- Branched out from `RADIO` branch, kindly review this [PR](https://github.com/LifeSG/web-frontend-engine/pull/13) first
- Fix incorrect behaviour for `useCurrentDate` in `DateInput` which only updates local state, but not React Form Hook internal state
- Create TimePicker component and corresponding storybook (MOL-11617)
> Create time picker and radio button group components

- package-lock.json
- src/__tests__/components/frontend-engine/frontend-engine.spec.tsx
- src/components/elements/alert/types.ts
- src/components/elements/text/types.ts
- src/components/elements/wrapper/types.ts
- src/components/fields/checkbox-group/types.ts
- src/components/fields/chips/types.ts
- src/components/fields/contact-number/contact-number.tsx
- src/components/fields/contact-number/types.ts
- src/components/fields/date-input/date-input.tsx
- src/components/fields/date-input/types.ts
- src/components/fields/multi-select/types.ts
- src/components/fields/radio-button/types.ts
- src/components/fields/select/types.ts
- src/components/fields/submit-button/types.ts
- src/components/fields/textarea/types.ts
- src/components/fields/textfield/types.ts
- src/components/fields/time-picker/types.ts
- src/components/frontend-engine/frontend-engine.tsx
- src/components/frontend-engine/types.ts
- src/components/frontend-engine/yup/helper.ts
- src/components/types.ts
- src/stories/2-frontend-engine/frontend-engine.stories.tsx
- src/utils/date-time-helper.ts
- MOL-11754
- Updated Yup helper to track and handle custom defined yup conditions
- Added generic to various interfaces so it is possible to extend validation config
- Added generic to frontend engine component as a way to pass the custom config
- `<FrontendEngine<ICustomValidationRules> />`
- Added `formRef.addCustomValidation()` to add custom validation
> Custom validation

- package-lock.json
- package.json
- rollup.config.js
- scripts/build.sh
- scripts/ci.sh
- src/components/frontend-engine/yup/types.ts
- Add build.sh and ci.sh
- Improve rollup config and package.json
> Build pipeline

- src/__tests__/components/fields/submit/submit.spec.tsx
- src/components/fields/submit-button/submit-button.tsx
- src/components/fields/submit-button/types.ts
- src/stories/3-fields/submit-button/submit-button.stories.tsx
- MOL-12264
- Added "invalid-form" to disable submit button if form is invalid
- Ready to merge
- Keep branch
> [SUBMIT][WL] add "invalid-form" to submit button's disabled attribute

- src/__tests__/components/fields/date-input/date-input.spec.tsx
- src/components/fields/date-input/date-input.tsx
- src/components/fields/date-input/types.ts
- src/components/shared/error-messages.ts
- src/stories/3-fields/date-input/date-input.stories.tsx
- src/utils/date-time-helper.ts
- MOL-12343
- Added min / max date validation to date-input field
- Made corresponding update in validation-schema-generator: https://github.com/LifeSG/validation-schema-generator/pull/11
> Date validation

- src/__tests__/components/fields/date-input/date-input.spec.tsx
- src/components/fields/date-input/date-input.tsx
- MOL-12425
- parse date with correct date formatter in validators
- add tests to cover this scenario
> [DATEVAL][WL] fix date validation with different date format

- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/chips/chips.tsx
- src/components/fields/multi-select/multi-select.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/select/select.tsx
- src/components/frontend-engine/frontend-engine.tsx
- src/components/frontend-engine/types.ts
- src/stories/2-frontend-engine/frontend-engine.stories.tsx
- MOL-12427
- update fields to check against options and remove values when the corresponding option is removed
- checkbox-group
- chips
- multi-select
- radio-button
- select
- add `setValue` method to FrontendEngine
- test cases will be added after the PR is approved
> Update field values on updating schema

- src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx
- src/__tests__/components/fields/chips/chips.spec.tsx
- src/__tests__/components/fields/multi-select/multi-select.spec.tsx
- src/__tests__/components/fields/radio-button/radio-button.spec.tsx
- src/__tests__/components/fields/select/select.spec.tsx
- src/__tests__/components/frontend-engine/frontend-engine.spec.tsx
- MOL-12427
- add unit tests for options schema update behaviour and `setValue()`
> Options fix

- package-lock.json
- package.json
- bump to v1.0.0.alpha.2
- changelog added: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog
> [MISC][WL] v1.0.0.alpha.2

- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/components/elements/wrapper/conditional-renderer.tsx
- src/components/elements/wrapper/wrapper.tsx
- ready to merge to long-lived branch
> Skip applying validation schema if field is conditionally hidden

- src/__tests__/components/fields/radio-button/radio-button.spec.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/radio-button/types.ts
- src/stories/3-fields/radio-button/radio-button.stories.tsx
**Changes**
Added optional 'disabled' field for individual options in Radio component
> Disabled field for radio options

- src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx
- src/__tests__/components/fields/chips/chips.spec.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/checkbox-group/types.ts
- src/components/fields/chips/chips.tsx
- src/components/fields/chips/types.ts
- src/stories/3-fields/checkbox-group/checkbox-group.stories.tsx
- src/stories/3-fields/chips/chips.stories.tsx
**Changes**
Added optional 'disabled' field for individual options in Checkbox and Chips components
Modified Chips story props (options & disabled) to reflect current implementation
> Disabled field for checkbox & chips options

- src/components/fields/text-field/text-field.tsx
**Changes**
- Derive text-field type via uiType instead of using it directly
> [MISC][WL] derive text-field type via uiType instead of using it directly

- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/__tests__/components/fields/text-field/text-field.spec.tsx
**Changes**
- fix broken test cases with number fields
> [TESTS][WL] fix number field references in unit tests

- src/__tests__/components/fields/checkbox-group/checkbox-toggle-group.spec.tsx
- src/components/fields/checkbox-group/checkbox-group.styles.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/checkbox-group/types.ts
- src/stories/3-fields/checkbox-group/checkbox-group.stories.tsx
- src/stories/3-fields/checkbox-group/checkbox-toggle-group.stories.tsx
- src/stories/common.tsx
**Changes**
Add support for toggle component from DS https://designsystem.life.gov.sg/react/index.html?path=/story/data-input-toggle--toggle
- Add toggle component
- Add support for None option selection.
- Add stories for toggle component
-   You may refer to this https://jira.ship.gov.sg/browse/RBS-342
> [CHECK-BOX-TOGGLE][AMI|VM] Add checkbox toggle component

- src/__tests__/components/fields/radio-button/radio-toggle-button.spec.tsx
- src/components/fields/radio-button/radio-button.styles.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/radio-button/types.ts
- src/stories/3-fields/radio-button/radio-button.stories.tsx
- src/stories/3-fields/radio-button/radio-toggle-button.stories.tsx
**Changes**
Add support for radio toggle component from DS https://designsystem.life.gov.sg/react/index.html?path=/story/data-input-toggle--toggle
- Add radio toggle component
- Add stories for radio toggle component
-   You may refer to this https://jira.ship.gov.sg/browse/RBS-343
> [RADIO-TOGGLE][AMI|VM] Add radio toggle component

- package-lock.json
- package.json
**Changes**
- v1.0.0-alpha.4 release
- Regenerated package-lock to resolve yaml vulnerability
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog
> Release/v1.0.0 alpha.4

- package-lock.json
- package.json
- scripts/ci.sh
- src/__tests__/components/fields/date-field/date-field.spec.tsx
- src/__tests__/components/fields/radio-button/radio-image-button.spec.tsx
- src/components/fields/date-field/date-field.tsx
- src/components/fields/radio-button/radio-button.styles.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/radio-button/types.ts
- src/stories/3-fields/radio-button/radio-image-button.stories.tsx
**Changes**
- Add radio-image-button component
- Upgrade reaact-design-system to v1.1.0-canary.1
- Fix date-input and update unit tests
- Upgrade reaact-design-system to v1.1.0-canary.1 (breaks date-input)
-   You may refer to this https://jira.ship.gov.sg/browse/RBS-399
> Radio image button

- src/stories/3-fields/radio-button/radio-image-button.stories.tsx
… story.
**Changes**
- Remove irrelevant props from image-radio-btn
-   You may refer to this https://jira.ship.gov.sg/browse/RBS-399
> [RADIO-IMAGE-BTN][VM|DS] Remove irrelevant props from image-radio-btn

- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/multi-select/multi-select.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/select/select.tsx
- src/components/fields/textarea/textarea.styles.tsx
- src/components/fields/textarea/textarea.tsx
**Changes**
- Updated to use `input-textarea` to ensure correct aria-invalid attribute is used
- Update components to show error state
> Error state

- README.md
- src/components/frontend-engine/event/context-provider.tsx
**Changes**
- Wrap access to the `document` object in `useEffect` to resolve error when running in Nextjs repos
- also update DS dependency in readme to sync with package.json
> Fix ssr error

- package-lock.json
- package.json
- src/components/fields/textarea/textarea.tsx
**Changes**
- to be merged after [PR#73](https://github.com/LifeSG/web-frontend-engine/pull/73)
> [MISC][RL] Bump version

- src/components/fields/radio-button/radio-button.tsx
**Changes**
[BUGFIX][VM] Fix class styling not being pass down to container element
> [BUGFIX][VM] Fix class styling not being pass down to container element

- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/components/fields/image-upload/image-context/image-context.tsx
- src/components/fields/image-upload/image-input/file-item/file-item.tsx
- src/components/fields/image-upload/image-upload.tsx
- src/components/shared/prompt/prompt.styles.ts
- src/stories/3-fields/image-upload/image-upload.stories.tsx
- src/utils/file-helper.ts
**Changes**
- Misc fixes to address non-critical PR comments from https://github.com/LifeSG/web-frontend-engine/pull/25
> Image upload

- src/components/fields/chips/chips.styles.tsx
- src/components/fields/text-field/text-field.tsx
- src/components/fields/textarea/textarea.styles.tsx
- src/components/shared/chip/chip.styles.ts
- src/stories/3-fields/chips/chips.stories.tsx
- src/stories/5-custom/filter/filter-checkbox-item.stories.tsx
- src/stories/common.tsx
**Changes**
- resolved validation error with null / empty strings in numeric field (CCUBE-249)
- fixed layout issues if chips exceed the component width (CCUBE-188)
- fixed broken story links
> Misc fixes

- package-lock.json
- package.json
**Changes**
- v1.0.0-alpha.6
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v100-alpha6-draft
> [MISC][WL] v1.0.0-alpha.6

- package-lock.json
- package.json
**Changes**
[BUGFIX][WORKROUND] Temporaly moves rds from peer-deps to deps so that npm will handle transitive deps for fee correctly
-   You may refer to this docs: https://nodejs.org/en/blog/npm/peer-dependencies
- also :  https://blog.npmjs.org/post/618653678433435649/npm-v7-series-arborist-deep-dive.html
- https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencie
> [BUGFIX][WORKROUND] Temporaly moves rds from peer-deps to deps

- package-lock.json
- package.json
**Changes**
Update version to 1.0.0-alpha.7
> [MISC][YH] Update version to alpha7

- .gitlab-ci.yml
- .pipeline/library/.gitlab-ci.yml
- .pipeline/settings/.gitlab-ci.yml
**Changes**
Update to accommodate for Gitlab pipeline
-   [keep] branch (will update accordingly if pipeline fails)
> [MOL-12712][EC] add gitlab pipeline

- src/components/fields/chips/chips.styles.tsx
- src/components/fields/chips/chips.tsx
- src/components/fields/textarea/textarea.styles.tsx
- src/components/fields/textarea/textarea.tsx
Update the padding for chip as advised from ux
> [MOL-12691] Update padding for chips/pills

- src/components/fields/image-upload/image-input/image-input.styles.ts
- src/components/fields/image-upload/image-input/image-input.tsx
- src/components/shared/drag-upload/drag-upload.styles.ts
… and 
**Changes**
Image upload component
- Fix colour for image upload description
- Add drop files text
- Align "Add Photos" button the drop files text to right of component
-   You may refer to figma for the intended design
> Update image upload component

- .github/workflows/trigger-gitlab-pipeline.yml
> [MOL-12712][EC] trigger pipeline when main branch has push event

- package-lock.json
- package.json
**Changes**
Update version to 1.0.0-alpha.8
> [MISC][YH] Update version to alpha8

- .github/workflows/trigger-gitlab-pipeline.yml
> [MISC][EC] update github action template for standardisation

- src/components/fields/image-upload/image-input/image-input.tsx
**Changes**
Add semibold font weight to image upload label
-   Add semibold font weight to image upload label
> [MISC][YH] Add semibold font weight to image upload label

- .github/workflows/trigger-gitlab-pipeline.yml
> [MISC][EC] update trigger with variable

- src/components/fields/text-field/text-field.tsx
**Changes**
- prevent caret from jumping to the end on change for email, numeric and text fields
- fix for contact field will be done in design system
- refer to CCUBE-277
> prevent caret from jumping to the end on change

- .github/workflows/trigger-gitlab-pipeline.yml
> [MISC][EC] refactor curl cmd

- package-lock.json
- package.json
> [MISC][HA] Bump version

- src/components/fields/contact-field/contact-field.tsx
**Changes**
-  Delete branch
- Add fix to contact field to allow user to empty the field when there is a default value set
-   Add fix to contact field to allow user to empty the field when there is a default value set
> [MISC][YH] Add fix to contact field to allow user to empty field

- package-lock.json
- package.json
**Changes**
Bump version to 1.0.0-alpha10
> [MISC][YH] Update version to 1.0.0-alpha10

- .github/workflows/README.md
- .github/workflows/trigger-gitlab-pipeline.yml
- .prettierrc
**Changes**
-   add workflow file for gitlab pipeline
> [MISC][WS] add web frontend engine pipeline

- package-lock.json
- package.json
**Changes**
- update version to alpha.11
> [MISC][YH] Update version to alpha.11

- src/__tests__/components/frontend-engine/frontend-engine.spec.tsx
- src/components/elements/sections/sections.tsx
- src/components/elements/wrapper/wrapper.tsx
- src/stories/2-frontend-engine/frontend-engine.stories.tsx
- src/utils/hooks/use-form-schema.ts
**Changes**
- added overrideSchema to useFormSchema
- allow overriding of sections
> add overrideSchema to useFormSchema

- package-lock.json
- package.json
**Changes**
- Do not merge yet
- bump to alpha.12
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v100-alpha12-draft
> [MISC][WL] v1.0.0-alpha.12

- package-lock.json
- package.json
**Changes**
- Update version to alpha 13
> [MISC][YH] Update version to alpha 13

- src/components/fields/location-field/location-helper.ts
- src/components/fields/location-field/location-modal/location-picker/location-picker.tsx
**Changes**
- replace use of leaflet in location-helper
- this fixes SSR error with rendering frontend engine
> replace use of leaflet in location-helper

- package-lock.json
- package.json
**Changes**
- bump to alpha.14
> v1.0.0-alpha.14

- src/__tests__/utils/location-helper.spec.ts
**Changes**
- Add new test file for location-helper
- Add test for fetchLocationList helper function error handling
> [MOL-13378][MA] add test for fetchLocationList helper function

- src/__tests__/components/fields/location-field/location-field.spec.tsx
- src/components/fields/location-field/location-helper.ts
- src/components/fields/location-field/location-modal/location-search/location-search.tsx
**Changes**
- Fix issue when default location is a pin location and user opens the map modal again
-    Fix issue when default location is a pin location and user opens the map modal again
> Mol 13392 fix

- package-lock.json
- package.json
**Changes**
- Update version to alpha.15
> [MISC][YH] Update version to alpha.15

- README.md
- package-lock.json
- package.json
- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/__tests__/components/fields/contact-field/contact-field.spec.tsx
- src/__tests__/components/fields/date-field/date-field.spec.tsx
- src/__tests__/components/fields/multi-select/multi-select.spec.tsx
- src/__tests__/components/fields/range-select/range-select.spec.tsx
- src/__tests__/components/fields/select/select.spec.tsx
- src/components/fields/date-field/date-field.tsx
- src/components/fields/date-field/types.ts
- src/components/fields/multi-select/multi-select.tsx
- src/components/fields/multi-select/types.ts
- src/components/fields/range-select/range-select.tsx
- src/components/fields/range-select/types.ts
- src/components/fields/select/select.tsx
- src/components/fields/time-field/time-field.tsx
- src/components/shared/error-messages.tsx
- src/stories/3-fields/date-field/date-field.stories.tsx
- src/stories/3-fields/range-select/range-select.stories.tsx
**Changes**
- Updated to use design system v2.0.0
- Reverted to using design system as peer dependency
- Date field
- New excludedDates validation rules to disable specific dates
- future, past, notFuture, notPast, minDate, maxDate rules now disable invalid dates
- New allowDisabledSelection option to allow selecting disabled dates
- Fixed broken tests
> Design system v2

- src/__tests__/components/fields/contact-field/contact-field.spec.tsx
- src/components/fields/contact-field/contact-field.tsx
- src/components/fields/contact-field/data.ts
- src/components/fields/contact-field/utils.ts
- src/stories/3-fields/contact-field/contact-field.stories.tsx
- prepend country code if not provided
- switch to country if different country code provided
- ignore if country codes does not match for fixed countries
> Contact field handling of defaultValues

- package-lock.json
- package.json
**Changes**
- Bump to v1.0.0-alpha.16
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v100-alpha16-draft
> [MISC][WL] v1.0.0-alpha.16

- .github/ISSUE_TEMPLATE/bug_report.md
**Changes**
- added bug reporting template
> add bug reporting template

- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/components/elements/wrapper/conditional-renderer.tsx
**Changes**
- Ensure default values of hidden fields at any level of nesting are excluded on change/submission by explicitly unregistering them
- `ConditionalRenderer` has to handle nested chip textarea
- The unregister logic for the textarea in `chips.tsx` has to stay because `ConditionalRenderer` can't handle the case where chips is shown, but textarea is not
- Remove prefilled values of hidden fields from form state
> Unregister conditionally rendered fields

- src/__tests__/components/fields/date-range-field/date-range-field.spec.tsx
- src/components/fields/date-range-field/date-range-field.tsx
- src/components/fields/date-range-field/index.ts
- src/components/fields/date-range-field/types.ts
- src/components/fields/index.ts
- src/components/frontend-engine/types.ts
- src/components/shared/error-messages.tsx
- src/stories/3-fields/date-range-field/date-range-field.stories.tsx
- src/utils/ts-helper.ts
**Changes**
- Add date range component
-   You may refer to this [RBS-427](https://jira.ship.gov.sg/browse/RBS-427)
> [RBS-427][VM] Add date range component

- package-lock.json
- package.json
**Changes**
- Bump to v1.0.0-alpha.17
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v100-alpha17-draft
> [MISC][WL] v1.0.0-alpha.17

- src/components/fields/location-field/location-modal/location-picker/location-picker.tsx
**Changes**
- Changed onemap tile url to new version
- Updated to use new attribution format
- Updated guide to use new map: https://www.onemap.gov.sg/docs/maps/
> [LOCATION][WL] switch to use new url scheme for onemap map tile

- src/__tests__/components/fields/range-select/range-select.spec.tsx
- src/components/fields/range-select/range-select.tsx
**Changes**
- fixed bugs on the rangeSelect component
- added new test cases
-   You may refer to this [RBS-668](https://jira.ship.gov.sg/browse/RBS-668)
> [RBS-668][IT] fixed bugs on the updated RangeSelect component

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog
- Bump to full version as a consuming service is going into production
> [MISC][WL] v1.0.0

- src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx
- src/__tests__/components/fields/checkbox-group/checkbox-toggle-group.spec.tsx
- src/__tests__/components/fields/chips/chips.spec.tsx
- src/__tests__/components/fields/contact-field/contact-field.spec.tsx
- src/__tests__/components/fields/date-field/date-field.spec.tsx
- src/__tests__/components/fields/multi-select/multi-select.spec.tsx
- src/__tests__/components/fields/radio-button/radio-button.spec.tsx
- src/__tests__/components/fields/radio-button/radio-image-button.spec.tsx
- src/__tests__/components/fields/radio-button/radio-toggle-button.spec.tsx
- src/__tests__/components/fields/range-select/range-select.spec.tsx
- src/__tests__/components/fields/select/select.spec.tsx
- src/__tests__/components/fields/switch/switch.spec.tsx
- src/__tests__/components/fields/text-field/email-field.spec.tsx
- src/__tests__/components/fields/text-field/numeric-field.spec.tsx
- src/__tests__/components/fields/text-field/text-field.spec.tsx
- src/__tests__/components/fields/textarea/textarea.spec.tsx
- src/__tests__/components/fields/time-field/time-field.spec.tsx
- src/__tests__/components/fields/unit-number-field/unit-number.spec.tsx
**Changes**
- Added the test cases for isDirty state for rest of the fields
- Split test cases for email and numeric fields into new files
- Misc refactoring of test cases
> Dirty fields

- package-lock.json
- package.json
- src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx
- src/__tests__/components/fields/multi-select/multi-select.spec.tsx
- src/components/fields/chips/chips.tsx
- src/components/fields/image-upload/image-input/image-input.tsx
- src/components/fields/image-upload/image-review/image-review.tsx
- src/components/fields/image-upload/image-upload.tsx
- src/components/fields/image-upload/types.ts
- src/components/fields/location-field/location-field.tsx
- src/components/fields/location-field/location-input/location-input.tsx
- src/components/fields/location-field/location-modal/location-modal.tsx
- src/components/fields/location-field/location-modal/location-picker/location-picker.tsx
- src/components/fields/location-field/location-modal/location-search/location-search.tsx
- src/components/fields/location-field/location-modal/location-search/types.ts
- src/components/fields/textarea/textarea.tsx
**Changes**
- Added className support to:
- chips textarea
- image-upload
- location-field
- textarea chips
- Bumped design system to v2.1.0-canary.5 to add className support for:
- contact
- multi-select
- range-select
- select
- unit-number-field
> Class names

- package-lock.json
- src/services/onemap/onemap-service.ts
**Changes**
- switched to use new onemap domain for static map, address search
- regenerated package lock to fix npm audit vulnerabilities
> Onemap migration

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v101-draft
> [MISC][WL] v1.0.1

- src/__tests__/components/frontend-engine/frontend-engine.spec.tsx
- src/components/frontend-engine/frontend-engine.tsx
- src/components/frontend-engine/types.ts
- src/utils/hooks/use-form-values.ts
**Changes**
- added `payload` argument to `getValues()`
- this follows the same behaviour as how react-hook-form retrieves values (https://react-hook-form.com/docs/useform/getvalues)
> [GETVALUES][WL] add payload argument to getValues()

- src/__tests__/components/custom/filter/filter-checkbox.spec.tsx
- src/__tests__/components/custom/filter/filter-item.spec.tsx
- src/components/custom/filter/filter-checkbox/types.ts
- src/components/custom/filter/filter-item/types.ts
- src/components/custom/filter/filter/filter.tsx
- src/components/custom/filter/filter/types.ts
- src/stories/5-custom/filter/filter-checkbox-item.stories.tsx
- src/stories/5-custom/filter/filter-item.stories.tsx
- src/stories/common.tsx
- src/utils/object-helper.ts
**Changes**
- Added `clearBehavior` to filter-item and filter-checkbox schemas
- Added clearBehaviour stories
- Split existing stories into small parts
> Filter clear

- src/__tests__/components/frontend-engine/frontend-engine.spec.tsx
- src/components/custom/review/review.tsx
- src/components/elements/wrapper/field-wrapper.tsx
**Changes**
- Clear field validation config if field is removed through schema changes
> Clear validation on removing field

- package-lock.json
- package.json
**Changes**
- Bump to v1.1.2
- Changelog https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v112-draft
> [MISC][WL] v1.1.2

- src/__tests__/components/frontend-engine/yup/yup-helper.spec.ts
- src/components/frontend-engine/yup/helper.ts
**Changes**
- skip non-required validation for empty fields
- this fixes scenarios where non-required validation rules still run after emptying the fields
> skip non-required validation for empty fields

- package-lock.json
- package.json
**Changes**
- Changelog https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v113-draft
> [MISC][WL] v1.1.3

- README.md
- package-lock.json
- src/__tests__/components/elements/divider/divider.spec.tsx
- src/components/elements/divider/divider.tsx
- src/components/elements/divider/index.ts
- src/components/elements/divider/types.ts
- src/components/elements/index.ts
- src/components/elements/section/section.tsx
- src/components/elements/section/types.ts
- src/components/elements/types.ts
- src/stories/2-frontend-engine/frontend-engine.stories.tsx
- src/stories/4-elements/divider/divider.stories.tsx
- src/stories/4-elements/grid/grid.stories.tsx
- src/stories/common.tsx
**Changes**
- New `divider` element
- New `layoutType` for `section` to render grid layout
> Divider and grid layout

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v120-draft
> [MISC][WL] v1.2.0

- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/__tests__/components/fields/location-field/location-field.spec.tsx
- src/components/fields/location-field/location-field.styles.ts
- src/components/fields/location-field/location-field.tsx
- src/components/fields/location-field/location-input/location-input.tsx
- src/components/fields/location-field/types.ts
- src/components/shared/static-map/static-map.styles.ts
- src/components/shared/static-map/static-map.tsx
- src/stories/3-fields/location-field/location-field-events.stories.tsx
- src/stories/3-fields/location-field/location-field.stories.tsx
Location field requires a few enhancements:
Dispatch event when location modal is shown
Dispatch event when location modal is dismissed
Accept `disabled` key
Add unit tests and stories
> [CCUBE-556][DV] Location field enhancements

- src/__tests__/components/fields/date-field/date-field.spec.tsx
- src/__tests__/components/fields/date-range-field/date-range-field.spec.tsx
- src/components/fields/date-range-field/date-range-field.tsx
- src/components/fields/date-range-field/types.ts
- src/components/shared/error-messages.tsx
- src/stories/3-fields/date-range-field/date-range-field.stories.tsx
**Changes**
- add `notFuture` and `notPast` validation to date range field
> Date range validation

- src/__tests__/components/custom/review/review.spec.tsx
- src/components/custom/review/review.tsx
- src/components/custom/review/types.ts
- src/stories/5-custom/review/review-events.stories.tsx
- src/stories/5-custom/review/review.stories.tsx
- src/stories/common.tsx
REQUIREMENTS
Ability to set half / full width values
Mask / unmask uinfin option (To confirm exact behaviour)
Optional button
Fire click event on clicking button
PROPOSED SCHEMA
{
"referenceKey": "review",
"variant": "accordion",
"label": "Your personal information",
"description": "Retrieved on 27 Jun 2023",
"button": {
"label": "Edit"
},
"collapsible":  true,
"expanded": false,
"items": [
{
"label": "Name (as in NRIC or passport)",
"value": "Tom Tan Li Ho",
"displayWidth": "half"
},
{
"label": "NRIC or FIN",
"value": "S••••534J",
"displayWidth": "half"
},
{
"label": "Date of birth",
"value": "6 November 1992",
"displayWidth": "half"
},
{
"label": "Residential Address",
"value": "Block 287, #05-11, Tampines street 22, Singapore 534788",
"displayWidth": "full"
},
{
"label": "Ethnicity", …
> [CCUBE-547][DV] Update review component to support accordion variant

- src/components/types.ts
**Changes**
- export types for external use
> [MISC][WL] export types for external use

- package-lock.json
- package.json
**Changes**
Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v121-draft
> [MISC][WL] v1.2.1

- src/__tests__/components/fields/button/button.spec.tsx
- src/components/fields/button/button.tsx
- src/components/fields/button/index.ts
- src/components/fields/button/types.ts
- src/components/fields/index.ts
- src/components/fields/types.ts
- src/stories/3-fields/button/button.stories.tsx
new FEE button uiType
button is based on Design System: https://designsystem.life.gov.sg/react/index.html?path=/story/general-button--button
icons are based on Design System: https://designsystem.life.gov.sg/reacticons/index.html?path=/story/collection--page
offer ability to prepend / append DS icons to button
dispatchFieldEvent on click
> [CCUBE-619][DV]Icon button inside a section - dispatch click event

- src/__tests__/components/custom/filter/filter-checkbox.spec.tsx
- src/__tests__/components/custom/filter/filter-item.spec.tsx
- src/components/custom/filter/filter-checkbox/filter-checkbox.tsx
- src/components/custom/filter/filter-checkbox/types.ts
- src/components/custom/filter/filter-item/filter-item.tsx
- src/components/custom/filter/filter-item/types.ts
- src/stories/5-custom/filter/filter-checkbox-item.stories.tsx
- src/stories/5-custom/filter/filter-item.stories.tsx
- src/stories/5-custom/filter/filter.stories.tsx
**Changes**
-   add ~~initialExpanded~~ expanded to IFilterCheckboxSchema and IFilterItemSchema
-  pass down ~~initialExpanded~~ expanded to Filter.Item component
-  add ~~InitialExpanded~~ expanded story for  FilterCheckbox and FilterItem
-  add unit test for Filter Item and Filter Checkbox as it's now a controlled behaviour
> [MISC ]Add InitialExpanded props to filter item

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v130-draft
> [MISC][WL] 1.3.0

- src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx
- src/__tests__/components/fields/radio-button/radio-button.spec.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/stories/3-fields/checkbox-group/checkbox-group.stories.tsx
- src/stories/3-fields/radio-button/radio-button.stories.tsx
**Changes**
- Allow html text for checkbox and radio button labels
> Option label

- package-lock.json
- package.json
**Changes**
- Bump version in package.json / package-lock.json
> [MISC][WL] v1.3.1

- package-lock.json
- package.json
- src/__tests__/components/fields/nested-multi-select/nested-multi-select.spec.tsx
- src/components/fields/index.ts
- src/components/fields/nested-multi-select/index.ts
- src/components/fields/nested-multi-select/nested-multi-select.tsx
- src/components/fields/nested-multi-select/types.ts
- src/components/fields/types.ts
- src/stories/3-fields/nested-multi-select/nested-multi-select.stories.tsx
**Changes**
- Added a new component, nested multi-select.
- Added relevant tests and stories
-   [keep] branch
-  Added new nested multi-select component
-   You may refer to [RBS-952](https://jira.ship.gov.sg/browse/RBS-952)
-   Awaiting bugfixes in DS
> [RBS-952] Nested multi-select component 

- package-lock.json
- package.json
- src/__tests__/components/fields/nested-multi-select/nested-multi-select.spec.tsx
- src/components/fields/index.ts
- src/components/fields/nested-multi-select/index.ts
- src/components/fields/nested-multi-select/nested-multi-select.tsx
- src/components/fields/nested-multi-select/types.ts
- src/components/fields/types.ts
- src/stories/3-fields/nested-multi-select/nested-multi-select.stories.tsx
**Changes**
Added nested-multi-select component
-  You may refer to [RBS-952](https://jira.ship.gov.sg/browse/RBS-952)
- Main branch to be merged into master
- Addressed issues mentioned in the previous branch
> [RBS 952] - Nested multi select component

- package-lock.json
- package.json
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v140-upcoming
> [MISC][RL] v1.4.0

- README.md
- package-lock.json
- package.json
- src/stories/5-custom/filter/filter-checkbox-item.stories.tsx
- src/stories/5-custom/filter/filter-item.stories.tsx
**Changes**
- Update filter checkbox and filter item `expanded` prop to be true by default
-   `filter-item` and `filter-checkbox` are now expanded by default
> default filter expanded to true

- src/__tests__/components/elements/alert/alert.spec.tsx
- src/__tests__/components/elements/text/text.spec.tsx
- src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx
- src/__tests__/components/fields/radio-button/radio-button.spec.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/radio-button/radio-button.tsx
**Changes**
- remove false positive assertion of js call in sanitize test cases
> remove assertion of console.log in sanitize tests

- src/components/shared/error-messages.tsx
> [MISC][RL] Remove duplicate error message

- src/components/elements/wrapper/field-wrapper.tsx
**Changes**
- Ensure useEffect clean up can access the latest value of restore mode
-   Ensure latest value is accessed when `restoreMode` is updated
> Get latest restore mode

- .vscode/settings.json
- src/__tests__/components/fields/file-upload/file-upload-helper.spec.ts
- src/__tests__/components/fields/file-upload/file-upload.spec.tsx
- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/components/fields/file-upload/file-upload-context.tsx
- src/components/fields/file-upload/file-upload-helper.ts
- src/components/fields/file-upload/file-upload-manager.ts
- src/components/fields/file-upload/file-upload.tsx
- src/components/fields/file-upload/index.ts
- src/components/fields/file-upload/types.ts
- src/components/fields/image-upload/image-manager/image-manager.ts
- src/components/fields/index.ts
- src/components/fields/types.ts
- src/stories/3-fields/file-upload/file-upload.stories.tsx
- src/utils/file-helper.ts
- src/utils/image-helper.ts
**Changes**
- New file upload field based on [DS FileUpload component](https://designsystem.life.gov.sg/react/index.html?path=/docs/modules-fileupload--docs)
- Structurally similar to existing `image-upload` field because `file-upload` field will be enhanced to cover `image-upload` field in the future
- Supports `base64` and `multipart` uploads
> File upload

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v160-draft
> [MISC][WL] v1.6.0

- src/__tests__/components/fields/text-field/text-field.spec.tsx
- src/components/fields/text-field/text-field.tsx
- src/components/fields/text-field/types.ts
- src/stories/3-fields/email-field/email-field.stories.tsx
- src/stories/3-fields/text-field/text-field.stories.tsx
-   Adding custom option to allow text and email inputs to be uppercase
> [BOOKINGSG-5240][WS|GC] text and email fields to include uppercase custom option

- src/components/fields/checkbox-group/checkbox-group.styles.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/checkbox-group/types.ts
- src/components/fields/radio-button/radio-button.styles.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/radio-button/types.ts
- src/stories/3-fields/checkbox-group/checkbox-toggle-group.stories.tsx
- src/stories/3-fields/radio-button/radio-toggle-button.stories.tsx
1. add layoutType props to radio/checkbox toggles to render horizontally or vertically
2. update storybook to radio/checkbox toggles
> [CCUBE-983][WX] Support vertical radio and checkbox toggles

- package-lock.json
- package.json
- src/components/fields/file-upload/file-upload.tsx
- src/stories/3-fields/file-upload/file-upload.stories.tsx
**Changes**
- Bump to latest DS, no breaking changes expected
- Update `file-upload` title to support html strings
-   Support formatting in `file-upload` label
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/CCUBE-982)
> Support html markup in file upload title

- src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx
- src/__tests__/components/fields/checkbox-group/checkbox-toggle-group.spec.tsx
- src/__tests__/components/fields/radio-button/radio-button.spec.tsx
- src/__tests__/components/fields/radio-button/radio-image-button.spec.tsx
- src/__tests__/components/fields/radio-button/radio-toggle-button.spec.tsx
- src/components/elements/wrapper/conditional-renderer.tsx
- src/components/fields/checkbox-group/checkbox-group.styles.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/checkbox-group/types.ts
- src/components/fields/radio-button/radio-button.styles.tsx
- src/components/fields/radio-button/radio-button.tsx
- src/components/fields/radio-button/types.ts
- src/components/fields/types.ts
- src/stories/3-fields/checkbox-group/checkbox-group.stories.tsx
- src/stories/3-fields/checkbox-group/checkbox-toggle-group.stories.tsx
- src/stories/3-fields/radio-button/radio-button.stories.tsx
- src/stories/3-fields/radio-button/radio-image-button.stories.tsx
- src/stories/3-fields/radio-button/radio-toggle-button.stories.tsx
**Changes**
- similar handling was implemented in validation-schema-generator: https://github.com/LifeSG/validation-schema-generator/pull/45
-   Support nested fields in checkbox and radio toggles
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/CCUBE-984)
> Support nested fields in checkbox and radio toggles

- src/__tests__/components/fields/location-field/location-field.spec.tsx
- src/components/fields/location-field/location-field.tsx
- src/components/fields/location-field/location-modal/location-modal.tsx
- src/components/fields/location-field/location-modal/location-search/location-search.styles.ts
- src/components/fields/location-field/location-modal/location-search/location-search.tsx
- src/components/fields/location-field/location-modal/location-search/types.ts
- src/components/fields/location-field/location-modal/types.ts
- src/components/fields/location-field/types.ts
- src/stories/3-fields/location-field/location-field.stories.tsx
**Changes**
port over disabling of search by input field
-   You may refer to this [MOL-15137](https://jira.ship.gov.sg/browse/MOL-15137)
> [MOL-15137][TY] port over disabling of search by input field

- src/stories/3-fields/location-field/location-field.stories.tsx
**Changes**
- update hasExplicitEdit storybook description
- refer to [MOL-14931](https://jira.ship.gov.sg/browse/MOL-14931)
> [MOL-14931][CWH] Update hasExplicitEdit storybook description

- src/stories/3-fields/location-field/location-field-events.stories.tsx
**Changes**
- Update location field stories to include **hide permission modal**
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/MOL-15105) and this [PR](https://github.com/LifeSG/web-frontend-engine/pull/242)
> [MOL-15105][ES] Add hide permission modal to storybook

- README.md
- package-lock.json
- package.json
- src/components/fields/slider/types.ts
- src/stories/3-fields/slider/slider.stories.tsx
[CCUBE-1116][AC] add customOptions for indicator and bump design system version
**Changes**
1. Add showIndicatorLabel, indicatorLabelPrefix, indicatorLabelSuffix
-   You may refer to this [[ticket](url)](https://jira.ship.gov.sg/browse/CCUBE-1116)
> [CCUBE-1116][AC] add customOptions for indicator and bump design system version

- src/components/fields/file-upload/file-upload-manager.ts
- src/components/fields/image-upload/image-context/image-context.tsx
- src/components/fields/image-upload/image-input/file-item/file-item.tsx
- src/components/fields/image-upload/image-input/image-input.tsx
- src/components/fields/image-upload/image-manager/image-manager.ts
- src/components/fields/image-upload/image-review/image-review.tsx
- src/components/fields/image-upload/image-upload-helper.ts
- src/components/fields/image-upload/image-upload.tsx
- src/components/fields/image-upload/types.ts
- src/components/fields/location-field/location-modal/location-modal.tsx
- src/stories/3-fields/image-upload/image-upload-events.stories.tsx
- src/utils/id-helper.ts
- src/utils/index.ts
**Changes**
- Add ids to selected photos
- fire event when photo is done processing but before upload
- add event listener for custom validation of images
- add custom error message from custom validation event
[delete] branch
-  Add custom validation event to image upload component
-   You may refer to this [MOL-15180](https://jira.ship.gov.sg/browse/MOL-15180)
> MOL-15180 Custom validation on image upload

- src/components/fields/image-upload/image-input/image-input.tsx
**Changes**
dynamic error message showing `You can only upload X more photos` wasn't showing due to error in logic
fix was made by comparing code of old FEE
> [MISC][SW] fix MAX_FILES_WITH_REMAINING error message condition

- src/__tests__/components/fields/hidden-field/hidden-field.spec.tsx
- src/components/fields/hidden-field/hidden-field.tsx
- src/components/fields/hidden-field/types.ts
- src/stories/3-fields/hidden-field/hidden-field.stories.tsx
**Changes**
- Support for non-string data types in validation and conditional rendering
- Clean up props passed into component
> Hidden field enhancements

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v190-draft
> [MISC][WL] v1.9.0

- src/__tests__/components/fields/location-field/location-field.spec.tsx
- src/stories/3-fields/location-field/location-field-events.stories.tsx
**Changes**
update storybook for refesh-location event
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/MOL-15419)
> [MOL-15419] update storybook for refesh-location event

- src/__tests__/components/frontend-engine/frontend-engine.spec.tsx
- src/components/frontend-engine/frontend-engine.tsx
- src/components/frontend-engine/types.ts
- src/context-providers/yup/context-provider.tsx
- src/context-providers/yup/helper.ts
- src/context-providers/yup/types.ts
- src/stories/2-frontend-engine/frontend-engine.stories.tsx
- src/utils/hooks/use-validation-schema.ts
**Changes**
- apply custom validation rules per instance
- fixed issue where custom validation is not applied to existing forms
- this caters to scenario where there are multiple Frontend Engine instances and custom validation of the same name but of different logic is applied to different instances
> Scoped custom validation

- src/__tests__/components/fields/file-upload/file-upload.spec.tsx
- src/components/fields/file-upload/file-upload-manager.ts
- src/components/fields/file-upload/file-upload.tsx
- src/components/fields/file-upload/types.ts
- src/stories/3-fields/file-upload/file-upload.stories.tsx
- src/utils/file-helper.ts
- src/utils/image-helper.ts
**Changes**
-   Support image compression in `file-upload`
> Support image compression in file upload

- src/components/fields/image-upload/image-review/image-error/image-error.tsx
**Changes**
amend title of image exceed error in review modal
-   You may refer to this [MOL-15398](https://jira.ship.gov.sg/browse/MOL-15398)
> [MOL-15398][ZX] amend title of image exceed error in review modal

- src/__tests__/components/fields/location-field/location-field.spec.tsx
- src/components/fields/location-field/location-modal/location-modal.tsx
- src/components/fields/location-field/location-modal/location-search/location-search.tsx
> [MISC][SW] fire get-selectable-pins with default values

- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/components/fields/image-upload/image-input/file-item/file-item.styles.ts
- src/components/fields/image-upload/image-input/file-item/file-item.tsx
- src/components/fields/image-upload/image-manager/image-manager.ts
- src/components/fields/image-upload/image-review/image-review.tsx
- src/components/fields/image-upload/image-upload.tsx
- src/components/fields/image-upload/types.ts
- src/stories/3-fields/image-upload/image-upload-events.stories.tsx
Changes
1. new **dismiss-review-modal** event
- **removePendingImages** flag to specify if need to remove pending images / images that has not been uploaded
2. new **uploaded event**
- pass back IImage
4. rename **update-file-validation** to **update-image-status**
5. new **ERROR_CUSTOM_MUTED** image status
6. update **FileItem** to support **ERROR_CUSTOM_MUTED** to display error message without the styling of **isError** and thumbnail will be shown
-   You may refer to this [MOL-15191](https://jira.ship.gov.sg/browse/MOL-15191)
> [CCW] enhancement to image-review + FileItem

- src/components/fields/location-field/location-field.tsx
**Changes**
Fix edit button triggering submit and validation
-   You may refer to this [MOL-15754](https://jira.ship.gov.sg/browse/MOL-15754)
> [MOL-15754][SW] set button type for location edit button

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1102-draft
> [MISC][WL] v1.10.2

- package-lock.json
- package.json
**Changes**
- changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1103-draft
> [MISC][WL] v1.10.3

- src/__tests__/components/elements/accordion/accordion.spec.tsx
- src/components/elements/accordion/accordion.styles.ts
- src/components/elements/accordion/accordion.tsx
- src/components/elements/accordion/index.ts
- src/components/elements/accordion/types.ts
- src/components/elements/index.ts
- src/components/elements/types.ts
- src/stories/4-elements/accordion/accordion.stories.tsx
**Changes**
add a new Accodion element, under the hood is using a BoxContainer
-  add a new Accodion element
-   You may refer to this [BOOKINGSG-5751](https://jira.ship.gov.sg/browse/BOOKINGSG-5751)
> Bookingsg 5751

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1110-draft
> [MISC][WL] v1.11.0

- src/__tests__/components/fields/e-signature-field/e-signature-field.spec.tsx
- src/components/fields/e-signature-field/e-signature-field.tsx
**Changes**
- Dismiss loading indicator on upload error
- Update Yup object shape to better reflect actual submitted values
> Updates to e-signature-field

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1121
> [MISC][WL] v1.12.1

- src/__tests__/components/elements/text/text.spec.tsx
- src/components/elements/text/text.tsx
- src/stories/4-elements/text/text.stories.tsx
1. add img, br, p and span tags to be allowed to render html string
2. add test case to cover the change
> Support img tag rendering for text

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1130
> [MISC][WL] v1.13.0

- src/__tests__/components/fields/e-signature-field/e-signature-field.spec.tsx
- src/components/fields/e-signature-field/e-signature-field.styles.ts
- src/components/fields/e-signature-field/e-signature-field.tsx
- src/components/shared/error-messages.tsx
**Changes**
- Added ability to retry upload on failure through new retry button
- Show refresh page alert message on 3 consecutive failures
> Update e-signature-field error handling

- src/__tests__/components/fields/date-field/date-field.spec.tsx
- src/__tests__/components/fields/date-range-field/date-range-field.spec.tsx
- src/__tests__/components/fields/e-signature-field/e-signature-field.spec.tsx
- src/__tests__/components/fields/file-upload/file-upload.spec.tsx
- src/__tests__/components/fields/histogram-slider/histogram-slider.spec.tsx
- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/__tests__/components/fields/location-field/location-field.spec.tsx
- src/__tests__/components/fields/text-field/email-field.spec.tsx
- src/components/fields/date-field/date-field.tsx
- src/components/fields/date-field/types.ts
- src/components/fields/date-range-field/date-range-field.tsx
- src/components/fields/date-range-field/types.ts
- src/components/fields/e-signature-field/e-signature-field.tsx
- src/components/fields/e-signature-field/types.ts
- src/components/fields/file-upload/file-upload-manager.ts
- src/components/fields/file-upload/file-upload.tsx
- src/components/fields/file-upload/types.ts
- src/components/fields/histogram-slider/histogram-slider.tsx
- src/components/fields/histogram-slider/types.ts
- src/components/fields/image-upload/image-input/file-item/file-item.tsx
- src/components/fields/image-upload/types.ts
- src/components/fields/location-field/location-field.tsx
- src/components/fields/location-field/types.ts
- src/components/shared/error-messages.tsx
**Changes**
- end all error messages with a period
- allow customising of the error messages through the validation config in the schema
- note: customisation of error messages in image review modal is still not possible, it will be addressed when the need arises
> Error messages

- src/__tests__/components/custom/timeline/timeline.spec.tsx
- src/components/custom/timeline/index.ts
- src/components/custom/timeline/timeline.tsx
- src/components/custom/timeline/types.ts
- src/components/custom/types.ts
- src/stories/5-custom/timeline/timeline.stories.tsx
- src/stories/common.tsx
**Changes**
- add timeline component
- timeline item supports plain text, HTML text and FEE schema
> [TIMELINE][WL] add timeline component

- package-lock.json
- package.json
**Changes**
- https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1140
> [MISC][WL] v1.14.0

- package-lock.json
- package.json
- src/__tests__/components/fields/select-histogram/select-histogram.spec.tsx
- src/components/fields/index.ts
- src/components/fields/select-histogram/index.ts
- src/components/fields/select-histogram/select-histogram.tsx
- src/components/fields/select-histogram/types.ts
- src/components/fields/types.ts
- src/stories/3-fields/select-histogram/select-histogram.stories.tsx
1. add new uitype select-histogram for the new DS component SelectHistogram
2. allow customisation of select-histogram error messages
> [BOOKINGSG-5979] add new uitype select-histogram

- package-lock.json
- package.json
> [MISC][WX]v1.15.0

- src/components/elements/wrapper/conditional-renderer.tsx
- src/components/fields/text-field/text-field.tsx
**Changes**
- PR fixes 2 issues
1. unable to type `0` in empty field
2. conditional rendering not working with numeric field as the source field
> Numeric fix

- src/components/fields/image-upload/image-review/image-review.styles.ts
- src/components/fields/image-upload/image-review/image-review.tsx
- src/components/fields/image-upload/image-upload.tsx
- src/components/fields/image-upload/types.ts
**Changes**
-   add in new props field `imageReviewModalStyles` to image-upload component
-   to append style in image review modal box
-   [MOL-16632](https://jira.ship.gov.sg/browse/MOL-16632)
> [MOL-16632][CWH] Allow custom image review modal styles

- src/stories/3-fields/image-upload/image-upload-events.stories.tsx
**Changes**
- add details about camera permissions to mount event
- simple fix for now - stories are to be streamlined / revamped in the future
> update image upload story for mount event

- package-lock.json
- package.json
**Changes**
- changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1180
> [MISC][WL] v1.18.0

- package-lock.json
- package.json
- changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1181
> [MISC][WL] v1.18.1

- src/components/shared/error-messages.tsx
**Changes**
fix copy change for maximum photo upload
-   You may refer to this [MOL-16826](https://jira.ship.gov.sg/browse/MOL-16826)
> [MOL-16826][TY] fix copy change for maximum photo upload

- README.md
- package-lock.json
- package.json
- src/__tests__/components/custom/review/review.spec.tsx
- src/components/custom/review/review.tsx
- src/components/custom/review/types.ts
- src/components/fields/histogram-slider/histogram-slider.tsx
- src/components/fields/histogram-slider/types.ts
- src/components/fields/select-histogram/select-histogram.tsx
- src/components/fields/select-histogram/types.ts
- src/stories/5-custom/review/review-box.stories.tsx
**Changes**
-   Support schema in `review` item value
-   Expose aria labels for slider inputs
> Bump design system to v2.8.0-canary.4

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1183
> [MISC][WL] v1.18.3

- package-lock.json
- package.json
- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/components/fields/image-upload/image-manager/image-manager.ts
- src/components/fields/image-upload/types.ts
- src/utils/image-helper.ts
**Changes**
- Extract date time and GPS from uploaded images.
-   You may refer to this [MOL-15397](https://jira.ship.gov.sg/browse/MOL-15397)
> [NL][Luna] extract datetime and gps from uploaded images

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1184
> [MISC][WL] v1.18.4

- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/__tests__/components/fields/date-field/date-field.spec.tsx
- src/__tests__/utils/date-time-helper.spec.ts
- src/components/fields/date-field/date-field.tsx
- src/components/fields/date-field/types.ts
- src/components/shared/error-messages.tsx
- src/context-providers/yup/custom-conditions/index.ts
- src/context-providers/yup/types.ts
- src/stories/2-frontend-engine/conditional-rendering/conditional-rendering.stories.tsx
- src/stories/3-fields/date-field/date-field.stories.tsx
- src/utils/date-time-helper.ts
**Changes**
Validate if value is within x days more or less from now or specific date
Add validation rule to date-field also as a general conditional rendering rule 
-   You may refer to this [CCUBE-1614](https://jira.ship.gov.sg/browse/CCUBE-1614)
> [CCUBE-1614][JON]Add withinDays condition to FEE

- package-lock.json
- package.json
**Changes**
- https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1185
> [MISC][WL] v1.18.5

- src/__tests__/components/custom/array-field/array-field.spec.tsx
- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/components/custom/array-field/array-field-element.tsx
- src/components/custom/array-field/array-field.tsx
**Changes**
- forward the main FEE behaviour mode config to the sub-FEE instances in `array-field`
> `array-field` form modes

- src/__tests__/components/custom/array-field/array-field.spec.tsx
- src/__tests__/components/custom/filter/filter-item.spec.tsx
- src/__tests__/components/custom/filter/filter.spec.tsx
- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/__tests__/components/elements/wrapper/wrapper.spec.tsx
- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/__tests__/components/fields/location-field/location-field.spec.tsx
- src/__tests__/components/fields/submit-button/submit-button.spec.tsx
- src/__tests__/components/frontend-engine/frontend-engine.spec.tsx
- src/components/fields/image-upload/image-review/image-review.styles.ts
- src/components/fields/image-upload/image-review/image-review.tsx
- src/components/fields/submit-button/submit-button.tsx
- src/components/frontend-engine/use-form-change.ts
- src/utils/hooks/use-validation-schema.ts
**Changes**
- Added support to perform async validation
- This feature is to support validation via postMessage for the upcoming iframe field
> Async validation

- src/__tests__/utils/date-time-helper.spec.ts
- src/components/fields/date-field/date-field.tsx
- src/components/fields/date-field/types.ts
- src/context-providers/yup/types.ts
- src/stories/2-frontend-engine/conditional-rendering/conditional-rendering-date.stories.tsx
- src/utils/date-time-helper.ts
**Changes**
Amend the date calculation logic to align with expectations
New features
- Add `inclusive` flag for `withinDays` validation and conditional rendering
Bug fixes
- Fix validation and conditional rendering failing for the last date in `withinDays`
- Exclude past/future dates for `beyondDays`
> Update days validation

- src/stories/2-frontend-engine/validation/validation.stories.tsx
> Update error message in validation stories for clarity

- src/components/fields/image-upload/image-input/image-input.styles.ts
**Changes**
-   update image upload description color
-   You may refer to this https://sgtechstack.atlassian.net/browse/MOL-17454
> [MOL-17454][CWH] Update image upload description color

- src/__tests__/components/fields/contact-field/contact-field.spec.tsx
- src/components/fields/contact-field/contact-field.tsx
- src/components/fields/contact-field/utils.ts
**Changes**
- Exclude the `3` prefix in Singapore house contact number validation
> Sg number validation

- package-lock.json
- package.json
**Changes**
-   bumping axios to v1.7.9 to address some vulnerability found during VAPT
> [MISC][CCW] bump axios to v1.7.9 to address VAPT

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1190
> [MISC][WL] v1.19.0

- src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx
- src/__tests__/components/frontend-engine/yup/yup-helper.spec.ts
- src/context-providers/yup/custom-conditions/index.ts
- src/context-providers/yup/types.ts
- src/stories/2-frontend-engine/conditional-rendering/conditional-rendering-string.stories.tsx
- src/stories/2-frontend-engine/validation/validation.stories.tsx
**Changes**
-   Add `notMatches` rule to validate if value does not match a given regex
-   Add `notEqualsField` rule to validate if value does not equal another field
> Add `notMatches` and `notEqualsField` rules

- src/__tests__/components/fields/checkbox-group/checkbox-toggle-group.spec.tsx
- src/components/fields/checkbox-group/checkbox-group.tsx
- src/components/fields/checkbox-group/types.ts
- src/stories/3-fields/checkbox-group/checkbox-toggle-group.stories.tsx
**Changes**
-   Description of change: Added sublabel option for checkbox toggle. Non-breaking change
-   You may refer to this ticket [https://sgtechstack.atlassian.net/browse/BOOKINGSG-6474]
> [BOOKINGSG-6474][CR] add sublabel prop for checkbox toggle

- package-lock.json
- package.json
**Changes**
- Change log: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1191
> [MISC][WL] v1.19.1

- package-lock.json
- package.json
**Changes**
- Change log: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1192
> [MISC][WL] v1.19.2

- package-lock.json
- package.json
**Changes**
- Alpha release for form-builder to resolve peer dependency conflicts and migrate to design system v3
> [MISC][WL] v2.0.0-alpha.1

- package-lock.json
- package.json
- src/stories/1-intro/form-builder/components/form-builder-tool.tsx
- src/stories/1-intro/form-builder/components/schema-view.tsx
**Changes**
- Temporarily remove form-builder package for build to succeed
> [MISC][WL] temporarily remove form-builder

- src/components/fields/location-field/location-field.tsx
- src/components/fields/location-field/location-helper.ts
- src/components/fields/location-field/location-modal/location-modal.tsx
- src/components/fields/location-field/location-modal/location-search/location-search.tsx
- src/components/fields/location-field/location-modal/location-search/types.ts
- src/components/fields/location-field/location-modal/types.ts
- src/components/fields/location-field/types.ts
- src/stories/3-fields/location-field/location-field.stories.tsx
**Changes**
-   You may refer to this [MOL-18260](https://sgtechstack.atlassian.net/browse/MOL-18260)
> [MOL-18260][NL] Add bufferRadius to location schema

- package-lock.json
- package.json
- src/stories/1-intro/form-builder/components/form-builder-tool.tsx
- src/stories/1-intro/form-builder/components/schema-view.tsx
**Changes**
- Merge to pre-release branch
- Install form-builder package
- Reinstate form builder stories
> [CCUBE-1703][WL] reinstate form-builder story

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog-(V2)#v200-alpha2
> [MISC][WL] v2.0.0-alpha.2

- src/__tests__/components/frontend-engine/yup/custom-conditions.spec.ts
- src/context-providers/yup/custom-conditions/index.ts
- src/context-providers/yup/custom-conditions/uen.ts
- src/context-providers/yup/types.ts
- src/stories/2-frontend-engine/validation/validation.stories.tsx
**Changes**
-   Add uen validation
-   You may refer to this [CCUBE-1776](https://sgtechstack.atlassian.net/browse/CCUBE-1776)
> [CCUBE-1776][HUY] Add Uen validation

- package-lock.json
- package.json
- src/__tests__/components/frontend-engine/yup/custom-conditions.spec.ts
- src/__tests__/components/frontend-engine/yup/yup-helper.spec.ts
- src/components/fields/location-field/location-field.tsx
- src/components/fields/location-field/location-helper.ts
- src/components/fields/location-field/location-modal/location-modal.tsx
- src/components/fields/location-field/location-modal/location-search/location-search.tsx
- src/components/fields/location-field/location-modal/location-search/types.ts
- src/components/fields/location-field/location-modal/types.ts
- src/components/fields/location-field/types.ts
- src/context-providers/yup/custom-conditions/index.ts
- src/context-providers/yup/custom-conditions/uen.ts
- src/context-providers/yup/helper.ts
- src/context-providers/yup/types.ts
- src/stories/2-frontend-engine/validation/validation.stories.tsx
- src/stories/3-fields/location-field/location-field.stories.tsx
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog-(V2)#v200-alpha3
- Changes are from main branch, did a merge to include the same changes
> Release/v2.0.0 alpha.3

- src/components/fields/file-upload/file-upload-manager.ts
- src/components/fields/file-upload/types.ts
- src/components/fields/image-upload/image-manager/image-manager.ts
- src/components/fields/image-upload/types.ts
- src/stories/3-fields/file-upload/file-upload.stories.tsx
- src/stories/3-fields/image-upload/image-upload.stories.tsx
**Changes**
update ImageUpload to accept sessionId in prop
-   You may refer to this [MOL-18172](https://sgtechstack.atlassian.net/browse/MOL-18172)
> [MOL-18172][ZX] update ImageUpload to accept sessionId in prop

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog-(V2)#v200-alpha6
> [MISC][WL] v2.0.0-alpha.6

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1197
> [MISC][WL] v1.19.7

- src/__tests__/components/fields/image-upload/image-upload.spec.tsx
- src/components/fields/image-upload/image-input/drag-upload/drag-upload.tsx
- src/components/fields/image-upload/image-review/image-thumbnails/image-thumbnails.tsx
**Changes**
Add a small delay to **handleInputChange** in **drag-upload** so the files can be loaded properly.
> [MOL-18941][TP] Fix issue image upload on some mobile devices

- package-lock.json
- package.json
**Changes**
Bump to axios 1.10.0
> [MISC][WS] testing axios version bump to 1.10.0

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog-(V2)#v200-alpha7
> Release/v2.0.0 alpha.7

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog#v1199
> [MISC][WL] v1.19.9

- README.md
- package-lock.json
- package.json
- src/__tests__/components/custom/filter/filter-checkbox.spec.tsx
- src/__tests__/components/custom/filter/filter-item.spec.tsx
- src/__tests__/components/custom/filter/filter.spec.tsx
- src/__tests__/components/elements/grid/grid.spec.tsx
- src/components/custom/array-field/array-field.tsx
- src/components/fields/checkbox-group/checkbox-group.styles.tsx
- src/components/fields/location-field/location-modal/location-modal.tsx
- src/components/fields/location-field/location-modal/location-picker/location-picker.tsx
- src/components/fields/location-field/location-modal/location-search/location-search.styles.ts
- src/components/fields/radio-button/radio-button.styles.tsx
- src/components/shared/chip/chip.styles.ts
- src/components/shared/static-map/static-map.tsx
- src/stories/1-intro/form-builder/components/form-builder-tool.styles.ts
- src/utils/hooks/use-window-helper.ts
**Changes**
Upgraded styled-components to v6
-   [BREAKING] Upgraded styled-components to v6
-   You may refer to this [ticket](https://sgtechstack.atlassian.net/browse/BOOKINGSG-7948)
> [BOOKINGSG-7948][NT] Upgraded styled-components to v6

- package-lock.json
- package.json
- src/components/custom/review/review.styles.ts
- src/components/custom/review/review.tsx
> Ccube 1925: Align review box margins in FEE

- src/__tests__/common/helper.tsx
- src/__tests__/components/custom/iframe/iframe.spec.tsx
- src/components/custom/iframe/iframe.tsx
- src/components/custom/iframe/types.ts
- src/components/custom/types.ts
- src/stories/5-custom/iframe/doc-elements/child-loading.tsx
- src/stories/5-custom/iframe/doc-elements/index.ts
- src/stories/5-custom/iframe/iframe.stories.tsx
**Changes**
- Port over iframe loading / loaded events implementation from v2 to v1
> (V1) Add loading / loaded events to iframe component 

- package-lock.json
- package.json
**Changes**
- Changelog: https://github.com/LifeSG/web-frontend-engine/wiki/Changelog-(V2)#v200-alpha12
> Release/v2.0.0 alpha.12

- .github/workflows/trigger-gitlab-pipeline.yml
**Changes**
- Allow making releases from `legacy/v1` branch
> [MISC][WL] allow releases from legacy/v1 branch
