src/components/fields/index.ts, src/components/fields/multi-select/index.ts, src/components/fields/multi-select/multi-select.tsx, src/components/fields/multi-select/types.ts, src/components/fields/select/select.tsx, src/components/fields/select/types.ts, src/components/fields/types.ts, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/stories/3-fields/multi-select/multi-select.stories.tsx, src/stories/3-fields/select/select.stories.tsx, src/stories/3-fields/submit-button/submit-button.stories.tsx, src/stories/common.ts, src/utils/index.ts, src/utils/object-helper.ts
- Created multi-select component and corresponding storybook
- Add transformation method for data in `FrontendEngine` prior to submission
- Transform data in `Select` from `{label: xxx, value: yyy}` to `yyy`
- Transform data in `MultiSelect` from `[{label: xxx, value: yyy}]` to `[yyy]`
- Refactor `Select` storybook according to updated JSON schema
- Update yup schema for `Select` and `MultiSelect`
=> Create multi-select component

src/components/fields/checkbox-group/checkbox-group.styles.tsx, src/components/fields/checkbox-group/checkbox-group.tsx, src/components/fields/index.ts, src/components/fields/radio-button/index.ts, src/components/fields/radio-button/radio-button.styles.tsx, src/components/fields/radio-button/radio-button.tsx, src/components/fields/radio-button/types.ts, src/components/frontend-engine/types.ts, src/stories/3-fields/radio-button/radio-button.stories.tsx
- Create `RadioButtonGroup` component and corresponding storybook (MOL-11617)
- Standardize container styling for `RadioButtonGroup` and `CheckboxGroup` to open up flexibility for CSS selectors
=> Create radio button group component

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/frontend-engine/frontend-engine.tsx, src/stories/2-frontend-engine/frontend-engine.stories.tsx
**Changes**
- Changed default `validationMode` from `onSubmit` to `onTouched`
-   Changed default `validationMode` to `onTouched`
- Reference of `onTouched` behaviour: https://react-hook-form.com/api/useform/#props
- Context: The `onTouched` behaviour is the behaviour that all our forms are using, have checked with UX and various teams regarding this
=> [VAL][WL] change default validationMode to onTouched

src/components/fields/checkbox-group/checkbox-group.styles.tsx, src/components/fields/checkbox-group/checkbox-group.tsx, src/components/fields/radio-button/radio-button.styles.tsx, src/components/fields/radio-button/radio-button.tsx
**Changes**
- ensure checkbox and radio button options are using the correct font / font-weight / line-height
- Open Sans, font-weight: regular, font-size: 1rem, line-height: 1.5rem
-   These texts were getting overridden by sgds css, have to use the DS's `Text` component to ensure the styling is correct
=> [MISC][WL] ensure checkbox and radio button use correct font

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/frontend-engine/event/context-provider.tsx, src/components/frontend-engine/event/index.ts, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/utils/hooks/index.ts, src/utils/hooks/use-field-event.ts
**Changes**
- Implement event listeners to frontend engine
- Implementation is from `image-upload` branch
- This is to be used by `image-upload` and `location-input` to fire LifeSG-specific events
- No stories added; they will be added for fields using events instead
=> Event listeners

src/components/frontend-engine/event/context-provider.tsx, src/utils/hooks/use-field-event.ts
**Changes**
- The previous change fixed SSR errors, but caused another issue. The useEffects run in the same render cycle, but the setState update to initialise the event manager only takes effect in the next render
- Instead of using state, a ref ensures the event manager reference is immediately updated
=> Fix event listener initialisation (again)

src/__tests__/components/fields/submit/submit.spec.tsx, src/components/fields/submit-button/submit-button.tsx, src/stories/3-fields/submit-button/submit-button.stories.tsx
**Changes**
- enable submit button if form is prefilled with valid values
- when submit button is configured to be disabled if form is invalid, it is not getting enabled even if form is prefilled with valid values
=> [SUBMIT][WL] update invalid-form mode to support form prefilling

src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx, src/components/elements/wrapper/conditional-renderer.tsx
**Changes**
- save form values to state in conditional render, this allows default values to be saved and used to decide if the children can be rendered
- this is to fix a bug when a field is pre-filled, the conditionally rendered fields are not rendered despite fulfilling the conditions
=> Fix conditional rendering behaviour when pre-filled

src/components/fields/image-upload/image-manager/image-manager.ts, src/components/fields/image-upload/image-upload.tsx, src/utils/hooks/use-validation-schema.ts
**Changes**
- Initialise validation schema with an empty Yup object
- Revert previous fix applied to image manager
- This fixes the broken test cases
- Related to https://github.com/LifeSG/web-frontend-engine/pull/86
- Error was happening when attempting to set value before the validation schema is initialised
- As such, initialising the validation schema with an empty Yup object will allow the value changes to go through
- This scenario is to cater to pre-filling so validation is not needed at this point - it will run again when user makes a change or do a submission
=> Validator fix

src/components/fields/location-field/location-helper.ts, src/utils/api-client/api-client.ts
**Changes**
- Add error handling logic for errors from Axios when request is aborted in location-helper.ts
- Remove unnecessary logic in error interceptor for api-client.ts
- Fixes on location-modal component
=> [MOL-13378][MA] handle error from aborted web requests

src/__tests__/components/custom/filter/filter-checkbox.spec.tsx, src/components/custom/filter/filter/filter.tsx
**Changes**
- Ensured filter values are cleared on clicking clear button
- Used `setValue()` instead of `resetField()` or `reset()` because react-hook-form will revert to `defaultValues` on reset
=> Ensure filter values are cleared on clicking clear button

src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx, src/components/elements/wrapper/conditional-renderer.tsx, src/components/elements/wrapper/field-wrapper.tsx, src/components/elements/wrapper/wrapper.tsx, src/components/fields/chips/chips.tsx, src/components/fields/reset-button/reset-button.tsx, src/components/frontend-engine/form-values/context-provider.tsx, src/components/frontend-engine/form-values/index.ts, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/stories/2-frontend-engine/conditional-rendering/conditional-rendering-array.stories.tsx, src/stories/2-frontend-engine/conditional-rendering/conditional-rendering-number.stories.tsx, src/stories/2-frontend-engine/conditional-rendering/conditional-rendering-restore-mode.stories.tsx, src/stories/2-frontend-engine/conditional-rendering/conditional-rendering-string.stories.tsx, src/stories/2-frontend-engine/conditional-rendering/conditional-rendering.stories.tsx, src/stories/2-frontend-engine/frontend-engine.stories.tsx, src/stories/5-custom/filter/filter-checkbox-item.stories.tsx, src/stories/common.tsx, src/utils/hooks/index.ts, src/utils/hooks/use-form-values.ts
**Changes**
- Track user's historical field inputs in a `FormValues` context
- Update fields on changes (via `watch`) and reset
- Introduce a `restoreMode` that configures how conditionally rendered fields are populated when they are toggled
- Added and reorganised stories under `Condtional Rendering/Rules` and `Condtional Rendering/Restoring Values`
=> Populate conditionally rendered fields

src/__tests__/components/frontend-engine/yup/custom-conditions.spec.ts, src/components/frontend-engine/yup/custom-conditions/uinfin.ts
**Changes**
- Skip uinfin validation if it is empty (that will be covered by `required` rule)
=> Skip uinfin validation if it is empty

src/components/fields/image-upload/image-input/file-item/file-item.styles.ts
**Changes**
- Update DeleteButton style to fix bug regarding styles not being applied to cross icon. 
- Previous implementation for DS v1 was designed to wrap the `Icon` component from `react-design-system` which contained a span, whereas the implementation in for DS v2 wraps a `CrossIcon` svg from `react-icons` hence removing the need for applied styles on spans
-   Fix style bug on cross icon for uploaded images
-   You may refer to [MOL-13719](https://jira.ship.gov.sg/browse/MOL-13719)
=> [MOL-13378][MA] fix styling for DeleteButton

src/__tests__/common/helper.tsx, src/__tests__/components/fields/contact-field/contact-field.spec.tsx, src/__tests__/components/fields/date-field/date-field.spec.tsx, src/__tests__/components/fields/image-upload/image-upload.spec.tsx, src/__tests__/components/fields/location-field/location-field.spec.tsx, src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/fields/contact-field/contact-field.tsx, src/components/fields/date-field/date-field.tsx, src/components/fields/image-upload/image-input/image-input.tsx, src/components/fields/image-upload/image-manager/image-manager.ts, src/components/fields/image-upload/image-review/image-review.styles.ts, src/components/fields/image-upload/image-review/image-review.tsx, src/components/fields/image-upload/image-review/image-thumbnails/image-thumbnails.styles.ts, src/components/fields/image-upload/image-upload.tsx, src/components/fields/image-upload/types.ts, src/components/fields/location-field/location-field.tsx, src/components/fields/location-field/location-modal/location-search/location-search.tsx, src/components/fields/location-field/location-modal/location-search/types.ts, src/components/fields/location-field/location-modal/types.ts, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/stories/2-frontend-engine/frontend-engine.stories.tsx
**Changes**
- added `isDirty` flag which can be referenced from frontend engine ref
- fixed setting of dirty states on mount / prefilling / reset for
- contact-field
- date-field
- image-upload
- location-field
- added test cases for frontend engine and the 5 components
- test cases for the remaining components will be added in another PR
=> `isDirty` flag

src/__tests__/components/fields/date-range-field/date-range-field.spec.tsx, src/__tests__/components/fields/image-upload/image-upload.spec.tsx, src/__tests__/components/fields/range-select/range-select.spec.tsx, src/__tests__/components/fields/time-field/time-field.spec.tsx, src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/elements/wrapper/field-wrapper.tsx, src/components/elements/wrapper/wrapper.tsx, src/components/frontend-engine/form-values/context-provider.tsx, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/stories/2-frontend-engine/frontend-engine.stories.tsx, src/utils/hooks/use-form-values.ts
**Changes**
- Added `stripUnknown` flag to schema, this gives the ability to exclude values of fields that are not declared in the schema
- Track registered field ids through form values context and FieldWrapper component
- Added `getFieldValues()` to filter according to `stripUnknown` flag on submit / `getValues()`
=> add `stripUnknown` flag to schema

src/__tests__/components/fields/location-field/location-field.spec.tsx, src/components/fields/location-field/location-field.tsx, src/components/fields/location-field/location-helper.ts, src/components/fields/location-field/location-modal/location-modal.tsx, src/components/fields/location-field/location-modal/location-search/location-search.tsx, src/components/fields/location-field/location-modal/location-search/types.ts, src/components/fields/location-field/location-modal/types.ts, src/components/fields/location-field/types.ts, src/services/onemap/onemap-service.ts, src/stories/3-fields/location-field/location-field.stories.tsx
**Changes**
Migrating changes from old mol-frontend-engine over
- choose nearest location in reverse geocode results to pin drop's lat lng instead of first result
- convert X Y from lat lng instead of using X Y from reverse geocode result
-  keep branch
-  You may refer to this [ticket](https://jira.ship.gov.sg/browse/MOL-13468)
-  **!!! Please merge the other [PR](https://github.com/LifeSG/web-frontend-engine/pull/157) first**
=> Migrating changes from old mol-frontend-engine over

src/components/fields/checkbox-group/checkbox-group.styles.tsx, src/components/fields/radio-button/radio-button.styles.tsx
**Changes**
- Prevent shrinking of checkboxes and radio buttons if the label is too long
=> Prevent shrinking checkboxes and radio buttons

src/components/custom/review/review.tsx
**Changes**
- updated `review` component to trigger `onChange` event on mount
- this allows forms with only review component to continue to use `onChange` event to get form state updates
- e.g. get form isValid state to enable/disable external submit button
=> update to trigger firing of onChange event

src/__tests__/components/fields/button/button.spec.tsx, src/components/fields/button/button.tsx, src/components/fields/button/types.ts, src/stories/3-fields/button/button.stories.tsx
**Changes**
- Replaced `renderStartIcon` and `renderEndIcon` with `renderIcon`
- Removed `loading` and `type` props, added `data-testid` prop
- Added click event assertion
- General refactoring of unit tests
- Added click event story
- Updated story props table
=> Button fixes

src/components/elements/section/section.styles.ts, src/components/elements/section/section.tsx, src/components/elements/section/types.ts, src/stories/4-elements/section/section.stories.tsx
**Changes**
- updated `section` uiType
- use `Layout.Content` for `grid layoutType with 0.75rem horizontal padding
- new contain layoutType to offer `Layout.Content` with block display
- added default layoutType
- added dedicated section stories
- section
- grid layoutType now comes with 0.75rem horizontal padding
- new contain layoutType that comes with 1320px max-width for general layout purposes
- new default layoutType to represent the standard layoutType
=> [SECTION][WL] update layoutType

src/components/fields/location-field/location-modal/location-search/location-search.tsx
- add in checking on `convertLatLngToXYEndpoint`
- ensure it is not undefined before calling `convertLatLngToXY`
- avoid error been trigger and cause the `onChangeSelectedAddressInfo` not be trigger
=> [MOL-14379][CWH] Fix convertLatLngToXYEndpoint undefined call error

src/components/custom/review/accordion-item/accordion-item.tsx
- console error of div being nested inside a p tag in accordion component
**Changes**
Changed html tag of maskedValues from div to span
=> [CCUBE-812][BL] Fixed bug issue of accordion component 

src/__tests__/components/fields/histogram-slider/histogram-slider.spec.tsx, src/components/fields/histogram-slider/histogram-slider.tsx, src/components/fields/histogram-slider/index.ts, src/components/fields/histogram-slider/types.ts, src/components/fields/index.ts, src/components/fields/types.ts, src/components/shared/error-messages.tsx, src/stories/3-fields/histogram-slider/histogram-slider.stories.tsx
**Changes**
- Port HistogramSlider, bumped DS to `2.3.0-canary.4` accordingly
- Value in the shape of `{ from: number; to: number; }`
- Support implicit validation through the `bins` and `interval` prop
-   New histogram slider field
=> Histogram slider

src/__tests__/components/frontend-engine/yup/yup-helper.spec.ts, src/components/frontend-engine/yup/helper.ts
**Changes**
- added fix for Yup's cyclic dependency error based on https://github.com/jquense/yup/issues/176#issuecomment-367352042
- this error happens when there fields with conditional validation that rely on each other
- e.g. field1 is required if field2 is empty and field2 is required if field1 is empty
- Yup is not able to determine which field comes first hence the error
- the workaround is to define the field pairs in the `shape()` method
=> add fix for cyclic dependency error

src/components/frontend-engine/yup/helper.ts
**Changes**
- ensure validation is applied regardless of key position
- validation is not getting applied when the condition is not declared 
- e.g. `{ "errorMessage": "this is an error", min: 5 }`
- this is happening because there is a check to ensure the conditions declared are what FEE is expecting
- but it is checking for the first property only, hence the error
- instead of that, now it checks all properties in a validation rule
=> [VALIDATION][WL] ensure validation is applied regardless of key position

src/components/frontend-engine/yup/helper.ts
**Changes**
- add optional chaining to schema reference when building conditional validation
- FEE may crash when a conditional validation rule is dependent on a field that has yet been added to the context
- This happens because each field is added incrementally
**Sample schema**
```
{
sections: {
section: {
uiType: "section",
children: {
"proxy-details-header": {
uiType: "text-h3",
children: "Proxy details",
},
"proxy-name": {
uiType: "text-field",
label: "Name",
validation: [
{
required: true,
errorMessage: "Please enter Name.",
},
{
matches: "/(^[^-\\s]{1}[a-zA-Z0-9_,'\\s-/@().]+$)|^$/",
errorMessage: "Invalid name. Try again.",
},
],
className: "short-width",
},
"proxy-phone-wrapper": {
uiType: "div",
className: "short-width …
```
=> add optional chaining to schema reference

README.md, jest/mocks/match-media.ts, package-lock.json, package.json, src/__tests__/common/tests/labels.ts, src/__tests__/components/custom/filter/filter-checkbox.spec.tsx, src/__tests__/components/custom/filter/filter.spec.tsx, src/__tests__/components/fields/chips/chips.spec.tsx, src/__tests__/components/fields/histogram-slider/histogram-slider.spec.tsx, src/__tests__/components/fields/slider/slider.spec.tsx, src/components/custom/filter/filter-checkbox/filter-checkbox.tsx, src/components/custom/filter/filter-item/filter-item.tsx, src/components/custom/filter/filter/filter.tsx, src/components/elements/wrapper/field-wrapper.tsx, src/stories/5-custom/filter/filter-checkbox-item.stories.tsx
**Changes**
-  Bump DS to latest canary
-  fix breaking tests for `hint` due to popover changes
- fix breaking tests for mobile version of `filter` by mocking media query
-  Add html support for option label in `filter-checkbox`
-   Add html support to `filter-checkbox` option label
=> Add html support to filter checkbox option label

src/__tests__/components/custom/filter/filter-checkbox.spec.tsx, src/__tests__/components/custom/filter/filter-item.spec.tsx, src/components/custom/filter/filter-checkbox/filter-checkbox.tsx, src/components/custom/filter/filter-checkbox/types.ts, src/components/custom/filter/filter-helper.tsx, src/components/custom/filter/filter-item/filter-item.tsx, src/components/custom/filter/filter-item/types.ts, src/components/custom/filter/types.ts, src/stories/5-custom/filter/filter-checkbox-item.stories.tsx, src/stories/5-custom/filter/filter-item.stories.tsx
**Changes**
- Add hint prop to filter item label to support tooltip popovers
- [This PR](https://github.com/LifeSG/web-frontend-engine/pull/217) should be merged first
-   Add popover to `filter-item`
=> Add popover to filter item

src/components/fields/image-upload/image-manager/image-manager.ts
**Changes**
- ensure base64 is of supported image type before compressing
- compression is failing when heic / heif files are added
- this is happening because the files are converted to base64 directly
- as these formats are not supported by browsers yet, the compression fails when they are converted to the image object
- fix is to generate base64 of a supported type first before converting to an image object
=> fix heic / heif compression

src/__tests__/components/fields/masked-field/masked-field.spec.tsx, src/components/fields/index.ts, src/components/fields/masked-field/index.ts, src/components/fields/masked-field/masked-field.tsx, src/components/fields/masked-field/types.ts, src/components/fields/types.ts, src/stories/3-fields/masked-field/masked-field.stories.tsx
**Changes**
- port `MaskedInput` from DS
- supports masking patterns with `maskRange`, `unmaskRange`, `maskChar` and `maskRegex`
- supports icon customisation with `iconActiveColor`, `iconInactiveColor`, `iconMask` and `iconUnmask`
- `transformInput` will format to uppercase or lowercase automatically
-   New uiType `masked-field`
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/CCUBE-980)
=> Masked field

src/__tests__/components/fields/location-field/location-field.spec.tsx, src/components/fields/location-field/location-field.tsx, src/components/fields/location-field/location-modal/location-modal.tsx, src/components/fields/location-field/location-modal/types.ts, src/components/fields/location-field/types.ts, src/stories/3-fields/location-field/location-field.stories.tsx
**Changes**
- Add `locationListTitle` prop to support functionality to update search results list title
- Add unit test for `locationListTitle`
- Update location-field stories
-   Ability to change `locationListTitle` from default 'Select location'
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/MOL-14960)
=> [MOL-14960][ES] Add functionality to update search results list title

package-lock.json
**Changes**
- downgrade react-hook-form to 7.47.0
- latest version is causing form to be dirty when `setValue()` is used
- this happens even if `shouldDirty: false` is set
=> [MISC][WL] downgrade react-hook-form to 7.47.0 to fix isDirty bug

src/__tests__/components/frontend-engine/yup/yup-helper.spec.ts, src/components/frontend-engine/yup/helper.ts, src/components/frontend-engine/yup/types.ts, src/stories/2-frontend-engine/validation/validation-conditional.stories.tsx
**Changes**
- add support for nested conditional validation
- note: this works for the `then` key only and doesn't work for `otherwise` key
- a similar implementation has already been added to validation-schema-generator: https://github.com/LifeSG/validation-schema-generator/pull/40
- Current implementation only supports `OR` conditional validations
- Having nested conditional validation fulfils the `AND` conditional validations
```
// OR
{
validation: [
{
when: {
field1: {
is: "",
then: "",
otherwise: "",
},
field2: {
is: "",
then: "",
otherwise: "",
}
}
}
]
}
// OR
{
validation: [
{
when: {
field1: {
is: "",
then: "",
otherwise: "",
}
}
},
{
when: {
field2: {
is: "",
then: "",
otherwise: "",
}
}
}
]
}
// AND
{
validation: [
{
when: {
field1: { …
```
=> [VALIDATION][WL] add support for nested conditional validation

src/__tests__/components/fields/location-field/location-field.spec.tsx, src/components/fields/location-field/location-modal/location-modal.tsx, src/components/fields/location-field/location-modal/location-search/location-search.tsx, src/stories/3-fields/location-field/location-field-events.stories.tsx
**Changes**
- dispatch field event `click-confirm-location` when click on confirm button in location modal
- add in event listener in location picker to handle the `confirm-location` which suppose to be trigger as a signal of finish of the `click-confirm-location` event
- Add unit test for confirm location button
- Update location-field stories
-   Add field event to confirm location button in location-picker modal
- refer to [MOL-15109](https://jira.ship.gov.sg/browse/MOL-15109)
=> [MOL-15109][CWH] Add field event to confirm location button

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/elements/section/types.ts, src/components/elements/sections/sections.tsx, src/components/elements/sections/types.ts, src/components/elements/wrapper/types.ts, src/components/elements/wrapper/wrapper.tsx, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/context-providers/yup/context-provider.tsx, src/stories/2-frontend-engine/frontend-engine.stories.tsx, src/utils/hooks/use-validation-schema.ts
**Changes**
- new `setWarnings()` function to set soft validation errors manually
- store warnings in yup context provider to share its value to nested children
-   New `setWarnings()` function to set soft validation errors manually
- Meant to display warning for illegal parking use case where there is a 250m proximity requirement for photos
=> Manually set soft validation errors (warnings)

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/fields/submit-button/submit-button.tsx, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/context-providers/context-providers.tsx, src/context-providers/frontend-engine-form/context-provider.tsx, src/context-providers/frontend-engine-form/index.ts, src/context-providers/index.ts, src/stories/2-frontend-engine/frontend-engine.stories.tsx, src/utils/hooks/index.ts, src/utils/hooks/use-form-values.ts, src/utils/hooks/use-frontend-engine-form.ts
**Changes**
- new `wrapInForm` prop to indicate whether to wrap Frontend Engine fields within the `<form>` element (defaults to true)
- ensure submit button can submit values without the <form> element
- new `FrontendEngineFormProvider` to share props with the submit button to perform manual submission
- refactored to use `describe.each` test suite to cover events in various `wrapInForm` values
- this is to support rendering `FrontendEngine` instances nested in other `FrontendEngine` instances
- because having nested `<form` element is not allowed, there is a need to prevent the rendering of form element
=> Wrap in form

src/components/elements/tab/tab.tsx
**Changes**
Quick fix for case where there is a common field between two tabs. Anything that triggers the useEffect to run again would cause the field to be removed
=> Prevent unnecessary tab children unregister

src/components/fields/image-upload/image-review/image-editor/image-editor.tsx
**Changes**
Had an error on local build where image cannot be compressed further, but the recursive compression kept being run with quality < 0.
according to [docs](https://fabricjs.com/docs/fabric.Canvas.html), `quality` prop value is 0-1.
added a check to stop recursive compression if quality is < 0
=> [MISC][SW] add check to end recursive image compression

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/types.ts, src/stories/2-frontend-engine/frontend-engine.stories.tsx
**Changes**
- new `validate()` to trigger validation
- exposes react-hook-form's `trigger()` method
- can trigger validation for the entire form / multiple fields / specific field
- this fixes issues in the PCI form's duplicate name / identification number checks
- in the scenario there are 2 validation errors, e.g. format + duplicate errors, fixing the duplicate error is clearing ALL errors now
- with this enhancement, we will trigger validation for that field only in order to bring up the remaining error
=> add validate method to trigger validation

src/components/fields/file-upload/file-upload.tsx
**Changes**
Ensure `uploadResponse` is populated if file is injected
-   Ensure `uploadResponse` is populated from default value for `file-upload`
**Additional info**
Example for testing:
```
export const MultipartUpload = DefaultStoryTemplate<IFileUploadSchema>("upload-multipart").bind({});
MultipartUpload.args = {
...COMMON_STORY_ARGS,
uploadOnAddingFile: {
type: "multipart",
url: "http://localhost:8080/file",
},
defaultValues: [
{
fileId: "iww8edcmbppi0x3vuaezkit770wmz4bbaj8g17mkhd7vx8g3q1ywtc",
fileName: "test.png",
fileUrl: "https://picsum.photos/id/237/200/300",
uploadResponse: {
data: {
fileUrl: "https://picsum.photos/id/237/200/300",
id: "3fe3ef72-1f19-45b4-a310-2d9785b95ad9",
},
},
},
],
};
```
Without the fix, the changed or submitted …
=> Apply file uploadResponse from default value

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/frontend-engine/frontend-engine.tsx
- update `setErrors()` to allow passing of error as object
- object is stringified to fit RHF's setError signature
- it will be up to component to parse error object
- this is for an upcoming enhancement to set error for individual image in `image-upload`
=> add ability to pass error as object in setErrors

src/components/fields/location-field/location-field.tsx, src/components/fields/location-field/location-modal/location-modal.tsx, src/components/fields/location-field/location-modal/types.ts, src/components/fields/location-field/types.ts
**Changes**
`addressFieldPlaceholder` can take in variable values but is not available in the schema typing.
added it to schema props and passed it down to `locationSearch`
-   Add addressFieldPlaceholder to location field schema
-   You may refer to this [MOL-15190](https://jira.ship.gov.sg/browse/MOL-15190)
=> [MOL-15190][SW] pass down addressFieldPlaceholder from schema

README.md, package-lock.json, package.json, src/__tests__/components/elements/alert/alert.spec.tsx, src/__tests__/components/fields/image-upload/image-upload.spec.tsx, src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/custom/filter/filter-checkbox/filter-checkbox.tsx, src/components/elements/list/list-item.tsx, src/components/elements/list/list.tsx, src/components/elements/text/text.tsx, src/components/elements/wrapper/field-wrapper.tsx, src/components/fields/checkbox-group/checkbox-group.tsx, src/components/fields/image-upload/image-input/image-input.styles.ts, src/components/fields/radio-button/radio-button.tsx, src/components/shared/sanitize/sanitize.tsx, src/stories/3-fields/image-upload/image-upload.stories.tsx
**Changes**
- use `Markup` to style parsed HTML content using the sanitize component
- this supports theming for link color etc.
-  [delete] branch
-   Apply default styling for HTML string children
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/CCUBE-1360)
=> Style HTML content

src/__tests__/components/frontend-engine/yup/yup-helper.spec.ts, src/components/fields/types.ts, src/context-providers/yup/helper.ts, src/context-providers/yup/types.ts
**Changes**
- added generics to `IYupValidationRule` to inherit custom validation typings for `then` and `otherwise` rules
- fixed issue with non-conditional validation rules not running when there are conditional validation rules
-   `then` and `otherwise` conditional validation typings now inherits custom validation typings
-   Ensure non-conditional validation rules can still work together with conditional validation rules
=> Conditional validation fixes

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/frontend-engine/frontend-engine.tsx
**Changes**
-  Fixed error not showing for nested field within radio button
-  Replaced id check using `getNestedValueByKey` with `registeredFields` because the former cannot check nested arrays which nested fields are based on
-   Ensure errors and warnings can be set for fields within radio buttons
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/CCUBE-1389)
=> CCUBE-1389: Fix error not showing for nested field within radio button

src/components/custom/filter/filter-item/types.ts, src/components/custom/filter/filter/types.ts, src/components/custom/types.ts, src/components/elements/grid/types.ts, src/components/elements/list/types.ts, src/components/elements/tab/types.ts, src/components/elements/types.ts, src/components/elements/wrapper/types.ts, src/components/fields/checkbox-group/types.ts, src/components/fields/radio-button/types.ts, src/components/fields/types.ts, src/components/frontend-engine/types.ts
**Changes**
- when custom schema interface is passed as a generic to frontend engine, ensure the typing is inherited in all other schemas
Example
```ts
interface MyCustomSchema extends TCustomComponentSchema<"my-custom-component", MyCustomRule> {
myCustomKey: string;
}
const JSON_SCHEMA: IFrontendEngineData<undefined, MyCustomSchema> = {
sections: {
section: {
uiType: "section",
children: {
wrapper: {
uiType: "div",
children: {
custom: {
referenceKey: "my-custom-component", // <-- this should be supported
myCustomKey: "hello", // <-- this should be supported
},
},
}
},
},
},
};```
=> Ensure custom schema typing is still inherited when nested in other schemas

src/components/fields/file-upload/file-upload-context.tsx, src/components/fields/file-upload/file-upload-manager.ts, src/components/fields/file-upload/file-upload.tsx, src/components/fields/file-upload/types.ts, src/components/fields/image-upload/image-context/image-context.tsx, src/components/fields/image-upload/image-manager/image-manager.ts, src/components/fields/image-upload/image-upload.tsx, src/components/fields/image-upload/types.ts
**Changes**
- The `handledFromDefault` flag is set in the field value, so it can leak across sessions and cause the file to be filtered out
```
// it's equivalent to doing this and the file is not reflected
DefaultValue.args = {
...COMMON_STORY_ARGS,
defaultValues: [
{
fileId: "file-1",
fileName: "test.jpg",
dataURL: jpgDataURL,
handledFromDefault: true,
},
],
};
```
- Had to find an alternative approach:
- First, using `isDirty` and `isTouched` to determine if default values should be handled
- Second, detect value changes. So the current uploaded files still need to be tracked
- Some issues with this
- Need a way to uniquely identify files - the file id seems to do the job (`generateRandomId` should be good enough?)
- `image-upload` does not track the id - have to generate for older …
=> Remove `handledFromDefault` from file and image upload field values

src/components/frontend-engine/frontend-engine.tsx
**Changes**
- Store `registeredFields` in a ref and have it update every time the actual object updates
- Update `setErrors` and `setWarnings` to check against this ref to ensure they get the latest value
=> check against ref in set errors / warnings

src/components/fields/location-field/location-field.tsx, src/components/fields/location-field/location-modal/location-modal.tsx, src/components/fields/location-field/location-modal/location-search/location-search.data.ts, src/components/fields/location-field/location-modal/location-search/location-search.tsx, src/components/fields/location-field/location-modal/location-search/types.ts, src/components/fields/location-field/location-modal/types.ts, src/components/fields/location-field/types.ts
**Changes**
Add option to location schema for the search bar to show the `location pin grey` icon.
Icon will default to the existing search icon
-   Location schema now takes in `searchBarIcon` prop
=> [MOL-15190][SW] add option to display different icon on location search bar

.eslintrc, README.md, package-lock.json, package.json, src/components/fields/checkbox-group/checkbox-group.styles.tsx, src/components/fields/checkbox-group/checkbox-group.tsx, src/components/fields/radio-button/radio-button.styles.tsx, src/components/fields/radio-button/radio-button.tsx, src/stories/3-fields/checkbox-group/checkbox-toggle-group.stories.tsx, src/stories/3-fields/radio-button/radio-toggle-button.stories.tsx
**Changes**
Renders the nested field for checkbox and radio options in the composite section instead of sublabel
However, this is a **breaking change** for styling as the new layout requires the consumer to apply the appropriate padding around the content
=> Render toggle nested fields in composite section

src/components/elements/wrapper/field-wrapper.tsx, src/components/fields/types.ts, src/stories/common.tsx
**Changes**
This is to cater for places that render FEE in a container with higher z-index. The popover appears to be missing because it shows behind the parent container
Can reproduce by wrapping the `DefaultStoryTemplate` with this and viewing any story with `Label Customisation`:
```
<div style={{ zIndex: 9, position: "relative", background: "pink", padding: "3rem" }}>
</div>
```
-   Allow overriding z-index of hint in the field label
=> Allow overriding z-index of field label hint

src/__tests__/components/fields/text-field/email-field.spec.tsx, src/__tests__/components/fields/text-field/numeric-field.spec.tsx, src/__tests__/components/fields/text-field/text-field.spec.tsx, src/components/fields/text-field/text-field.tsx, src/components/fields/text-field/types.ts, src/stories/3-fields/email-field/email-field.stories.tsx, src/stories/3-fields/numeric-field/numeric-field.stories.tsx, src/stories/3-fields/text-field/text-field.stories.tsx
**Changes**
Uses [DS InputGroup](https://designsystem.life.gov.sg/react/index.html?path=/docs/form-inputgroup--docs) to display add ons
-   Allow display of icon or label prefix/suffix in `text-field`
=> Support icon or label add-on in text field

README.md, package-lock.json, package.json, src/__tests__/common/helper.tsx, src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx, src/__tests__/components/fields/multi-select/multi-select.spec.tsx, src/__tests__/components/fields/select/select.spec.tsx, src/stories/3-fields/multi-select/multi-select.stories.tsx, src/stories/3-fields/select/select.stories.tsx
**Changes**
Bump DS peer dependency
Notable changes in `v2.7.0-canary.3`:
- select and multi-select have a new dropdown menu
- the `listStyleWidth` prop is deprecated - have removed the stories
- list items now have aria role `option` instead of being buttons - update selectors in unit tests
---
=> Update design system

README.md, package-lock.json, package.json, src/components/custom/filter/filter-checkbox/types.ts, src/components/custom/filter/filter/filter.tsx, src/components/custom/filter/filter/types.ts, src/stories/5-custom/filter/filter-checkbox-item.stories.tsx, src/stories/5-custom/filter/filter.stories.tsx, src/stories/5-custom/timeline/timeline.stories.tsx
**Changes**
- Bump DS version
- Fix deprecated storybook components for `Timeline`
- Add `toggleFilterButtonStyle` and `useToggleContentWidth` props for `Filter` & `FilterCheckbox` respectively (same props added in DS)
- Add optional `toggleFilterButtonStyle` prop for `Filter` component
- Add optional `useContentWidth` prop for `FilterCheckbox` component
-   You may refer to these [BOOKINGSG-6062](https://jira.ship.gov.sg/browse/BOOKINGSG-6062), [BOOKINGSG-5999](https://jira.ship.gov.sg/browse/BOOKINGSG-5999)
=> Add new optional DS props for Filter & FilterCheckbox

src/__tests__/components/elements/popover/popover.spec.tsx, src/components/elements/index.ts, src/components/elements/popover/index.ts, src/components/elements/popover/popover.styles.ts, src/components/elements/popover/popover.tsx, src/components/elements/popover/types.ts, src/components/elements/text/text.tsx, src/components/elements/text/types.ts, src/components/elements/types.ts, src/stories/4-elements/popover/popover.stories.tsx
**Changes**
Add popover element that renders an interactive text string and supports an optional icon based on the DS collection
It can be used standalone (with a parent container) or inline with text elements (see `Inline Usage` story)
The sanitisation behaviour in the text component was tweaked to prevent stripping of the inline svg icon. As a side effect, it seems to restore the paragraph styling
-   Add popover element
-   You may refer to this [ticket](https://jira.ship.gov.sg/browse/MOL-16147)
=> Create popover element

src/__tests__/components/elements/alert/alert.spec.tsx, src/components/elements/alert/alert.tsx, src/components/elements/alert/types.ts, src/stories/4-elements/alert/alert.stories.tsx
**Changes**
Add additional children type, used in JSON-only configs to have more control over the alert display
-   Support schema as children in `alert` element
=> Support FEE schema in alert children

src/components/fields/image-upload/image-input/drag-upload/drag-upload.tsx
**Changes**
This PR fixes an issue in the `image-upload` component where certain Android devices were unable to display all images in the gallery for uploading.
Before this fix, `image-upload` component was using "image/jpg". This fix calls the MIME type conversion util. The behaviour on iOS and Web remain unchanged.
- Updated the MIME type for JPEG images from "image/jpg" to "image/jpeg" in the `image-upload` component to resolve gallery image display issues on Android by calling the helper function.
-   You may refer to this [MOL-16463](https://jira.ship.gov.sg/browse/MOL-16463)
**Screenshots**
Before fix:
After fix:
=> [MOL-16463][XZY] Fix invalid jpg MIME type for image-upload

src/__tests__/components/fields/text-field/numeric-field.spec.tsx, src/components/fields/text-field/text-field.tsx
**Changes**
- updated numeric-field to deal with values as numbers instead of strings
-  Fixed `numeric-field` to submit values as numbers
-   You may refer to this [MOL-16566](https://jira.ship.gov.sg/browse/MOL-16566)
-   There was a bug reported that `numeric-field` cannot be submitted because the value is a string and not a number and that failed our backend validation
=> [NUMERIC][WL] update numeric-field to deal with values as numbers

src/components/custom/review/types.ts, src/components/elements/accordion/accordion.tsx, src/components/elements/accordion/types.ts, src/stories/4-elements/accordion/accordion.stories.tsx, src/stories/5-custom/review/review-box.stories.tsx
**Changes**
- Expose background prop in `review` box variant to support composition in other layouts
- Allow default content padding in `accordion` to be toggled, useful for layouts that need full-width content like dividers
-   Add `background` option for `review` box variant
- Support disabling of default content padding in `accordion`
=> Enhance review and accordion displays

src/__tests__/components/elements/wrapper/wrapper.spec.tsx, src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx, src/__tests__/components/fields/checkbox-group/checkbox-toggle-group.spec.tsx, src/__tests__/components/fields/radio-button/radio-button.spec.tsx, src/__tests__/components/fields/radio-button/radio-toggle-button.spec.tsx, src/components/custom/review/types.ts, src/components/elements/accordion/types.ts, src/components/elements/alert/types.ts, src/components/elements/list/types.ts, src/components/elements/section/types.ts, src/components/elements/tab/types.ts, src/components/elements/text/types.ts, src/components/elements/types.ts, src/components/elements/wrapper/types.ts, src/components/fields/checkbox-group/checkbox-group.tsx, src/components/fields/checkbox-group/types.ts, src/components/fields/error-field/types.ts, src/components/fields/radio-button/radio-button.tsx, src/components/fields/radio-button/types.ts, src/stories/3-fields/checkbox-group/checkbox-group.stories.tsx, src/stories/3-fields/checkbox-group/checkbox-toggle-group.stories.tsx, src/stories/3-fields/radio-button/radio-button.stories.tsx, src/stories/3-fields/radio-button/radio-toggle-button.stories.tsx, src/stories/4-elements/wrapper/wrapper.stories.tsx
**Changes**
- 38d9b1451bd132552dd3e8cd9ca868532250683e
- enhanced checkbox/radio option label to support schema. the use case is to support popover at any position 
- the children are restricted to [phrasing content](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#phrasing_content) which we can usually think of as "inline" elements (in terms of presentation). currently the inline elements in FEE are `popover` and `span`
- to restrict the typing of children, split up `IWrapperSchema` and `TElementSchema` to be more discrete
- 6028ab9ba9629b4577d150ef51c17428819dfecf
- `IWrapperSchema` renamed to `TWrapperSchema` as it's now a type, not an interface
- f666c0eb92a5dfaab92b53aeb2089680edfcaf56
- updating existing components that also restrict typing of children, to reuse …
=> Support schema label in checkbox and radio

src/__tests__/components/custom/filter/filter-checkbox.spec.tsx, src/__tests__/components/fields/checkbox-group/checkbox-group.spec.tsx, src/__tests__/components/fields/chips/chips.spec.tsx, src/__tests__/components/fields/multi-select/multi-select.spec.tsx, src/__tests__/components/fields/nested-multi-select/nested-multi-select.spec.tsx, src/__tests__/components/fields/radio-button/radio-button.spec.tsx, src/__tests__/components/fields/range-select/range-select.spec.tsx, src/__tests__/components/fields/select/select.spec.tsx, src/components/elements/sections/index.ts, src/components/elements/sections/sections.tsx, src/components/elements/sections/types.ts, src/components/frontend-engine/frontend-engine.tsx
**Changes**
- caused by field mounting before the overrides are loaded
- this is because `Sections` gets its schema from props and overrides from the context. the context is delayed by 1 render since it depends on `useEffect` to populate
- update `Sections` to get schema from form context, this ensures it renders the current schema in sync with its children
-   Fix prefill not working for `select` and `multi-select` when using overridden options
=> Fix prefilled option not populated for select field with overrides

src/__tests__/components/fields/radio-button/radio-toggle-button.spec.tsx, src/components/fields/radio-button/radio-button.tsx, src/components/fields/radio-button/types.ts, src/stories/3-fields/radio-button/radio-toggle-button.stories.tsx
**Changes**
Add `subLabel` prop for toggle radio button options
-   [WARNING] Radio buttons, with styleType set as `toggle`, can now accept an optional field called `subLabel`, which renders an additional block of text (i.e. `subLabel`) below the `label`.
-   This enhancement activates the following [DS component feature](https://designsystem.life.gov.sg/react/index.html?path=/docs/data-input-toggle-with-sub-label--docs).
- This FEE feature will be used in [this BSG-Appts2.0 ticket](https://jira.ship.gov.sg/browse/BOOKINGSG-6223).
=> [BOOKINGSG-6223][GC] add sublabel option for Toggle radio button option

src/components/fields/image-upload/image-input/file-item/file-item.styles.ts, src/components/fields/image-upload/image-input/file-item/file-item.tsx
**Changes**
- fix error message issue due to word-break: all, add in word break wrapper to filename
- remove fileNameWrapperRef from error message
-   You may refer to this [MOL-16871](https://jira.ship.gov.sg/browse/MOL-16871)
=> [MOL-16871][CWH] Add wrapper and apply word break only to filename

src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx, src/components/elements/wrapper/field-wrapper.tsx
**Changes**
- when `restoreMode=none`, allow boolean values to be cleared as well
**Note**
the clearing behaviour is still rather awkward and need further enhancements 
- setting `undefined` is the only way to clear numeric / boolean fields but it cannot be done in `reset` button because RHF dont accept `undefined` for reset. we need further enhancements to make all fields support `null` value and align the reset value
- we cant handle clearing of objects yet because every object is expecting a different shape, individual fields need to be enhanced to work with the clearing / reset
=> clear boolean values if restoreMode=none

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/components/frontend-engine/frontend-engine.tsx, src/components/frontend-engine/use-form-change.ts, src/context-providers/yup/helper.ts
**Changes**
`onValueChange` is not triggered when schema changes e.g. due to conditional rendering. This can cause the validity status to be stale. Detect when the form validation changes and trigger this callback accordingly
-   [WARNING] Trigger onValueChange when schema changes
=> Call onValueChange with latest validity when schema changes

src/__tests__/components/elements/wrapper/conditional-renderer.spec.tsx, src/components/elements/wrapper/field-wrapper.tsx
**Changes**
Force the field registration hook to run earlier using `useLayoutEffect` instead of `useEffect`
Makes this particular example work:
- conditionally rendered parent using the `shown` rule
- this `shown` rule depends on an overridden field
- child field (`b`) requires prefilling
- child field has a sibling field (`a`) that is also conditionally rendered
```
<FrontendEngine
data={{
sections: {
section: {
uiType: "section",
children: {
hidden: {
uiType: "div",
children: {},
},
wrapper: {
uiType: "div",
showIf: [{ test: [{ shown: true }] }],
children: {
a: {
label: "A",
uiType: "text-field",
showIf: [{ missing: [{ shown: true }] }],
},
b: {
label: "B",
uiType: "text-field",
},
},
},
},
},
},
defaultValues: {
b: "bye",
},
overrides: {
hidden: {
children: {
test: { uiType: …
```
=> Fix prefill for shown rule using overrides

src/components/fields/location-field/location-modal/location-modal.tsx, src/components/fields/location-field/location-modal/location-search/location-search.tsx
**Changes**
When populating the location from image metadata, clicking the location modal to open the map modal shows the location field as empty the first time but works correctly on subsequent attempts.
-   [ delete ] branch
-   You may refer to this [ticket](https://sgtechstack.atlassian.net/browse/MOL-15397)
=> [MOL-15397][NL] Fix location modal being empty on first load

src/__tests__/components/frontend-engine/frontend-engine.spec.tsx, src/context-providers/yup/helper.ts
**Changes**
- updated Yup custom validation to look for `yupId` in the correct place
- added test cases for applying custom validations for various data types
- error is reported when adding custom validation for `date-range-field`
- issue is with the checking of `yupId` in `const metaYupId = testContext.options["from"][0].schema.describe().meta.yupId;`
- it appears that when using `Yup.object()`, an extra entry is added to the from array, the last entry is the topmost layer where `yupId` is stored
=> Object custom validation

src/utils/file-helper.ts
**Changes**
- Fix jpg validation with file-upload
- Validation is failing because the derived ext is `jpeg` but our rule accepts `jpg` only
- Solution is to convert the derived ext to `jpg`
=> [FILE_UPLOAD][WL] fix jpg validation in file-upload

src/components/fields/image-upload/image-review/image-editor/image-editor.tsx, src/utils/file-helper.ts
**Changes**
Make sure it's checking the max file size in correct unit
-   To check for max file size correctly when compressing image after user draw on the image uploaded
-   You may refer to this [ticket](https://sgtechstack.atlassian.net/browse/MOL-17213)
=> [MOL-17213][WH] Fix image became pixelated after user drew on it issue

src/components/fields/textarea/textarea.styles.tsx, src/components/fields/textarea/textarea.tsx
**Changes**
The error message and counter texts are not aligned. This PR changes `Textarea` to use `Form.Textarea` instead of the standalone component (form version has this fixed)
- Fixed textarea error message and max length counter not being on the same line
=> Fix textarea error and max length counter not being on the same line

src/utils/file-helper.ts
**Changes**
-  Remove fileTypeFromBlob
- Get arrayBuffer from file/blob and get file type with fileTypeFromBuffer() function
-   You may refer to this [MOL-17297](https://sgtechstack.atlassian.net/browse/MOL-17297)
=> [MOL-17297][LD] Update to use fileTypeFromBuffer() instead of fileTypeFromBlob() in file-helper

src/__tests__/components/elements/accordion/accordion.spec.tsx, src/components/elements/accordion/accordion.tsx, src/components/elements/accordion/types.ts, src/stories/4-elements/accordion/accordion.stories.tsx
**Changes**
Currently, the accordion's title is fixed and not customisable. The new design calls for the title to be in "semibold" and a H4 element instead.
-   Update accordion element to allow for custom titles
-   You may refer to this [MOL-17410](https://sgtechstack.atlassian.net/browse/MOL-17410)
=> [MOL-17410][GW] Update accordion element to allow for custom titles

src/__tests__/components/fields/hidden-field/hidden-field.spec.tsx, src/components/fields/hidden-field/hidden-field.tsx, src/components/fields/hidden-field/types.ts, src/stories/3-fields/hidden-field/hidden-field.stories.tsx
**Changes**
- add `value` prop to `hidden-field`
- this will take precedence over form values and effectively force it to be uneditable
- for type safety, the typing has been updated so that `value` matches `valueType`. however this required converting the interface to a type
-   Set `hidden-field` value from schema to make the field uneditable
=> Set `hidden-field` value from schema

src/components/fields/textarea/textarea.tsx
**Changes**
-   Add focus on text area when chips are clicked to fix bug with onBlur validation not firing
-   You may refer to this ticket [MOL-17974](https://sgtechstack.atlassian.net/browse/MOL-17974)
=> [MOL-17974][MA] force focus on text area field when chips are clicked

src/components/custom/filter/filter-helper.tsx, src/components/custom/filter/types.ts, src/stories/5-custom/filter/filter-checkbox-item.stories.tsx, src/stories/5-custom/filter/filter-item.stories.tsx
**Changes**
Allow filter item/checkbox's label hint content to render schema, while not breaking any existing functionality
This allows us to configure the stylings within the content!!!
-   Allow filter hint content to render schema
=> [MOL-18369][GW] Allow filter hint content to render schema

src/__tests__/utils/file-helper.spec.ts, src/components/fields/file-upload/file-upload-manager.ts, src/components/fields/image-upload/image-manager/image-manager.ts, src/utils/file-helper.ts
**Changes**
This issue was discovered when uploading a MacOS screenshot in multipart upload. The backend received a filename containing additional characters that were not in the original filename.
```
original: Screenshot 2025-06-06 at 4.08.20 PM.png
received: Screenshot 2025-06-06 at 4.08.20â¯PM.png
```
On further inspection, the raw HTTP request contains the following data
```
------WebKitFormBoundary9BnO3UzfnbwLz22y
Content-Disposition: form-data; name="file"; filename="Screenshot 2025-06-06 at 4.08.20 PM.png"
```
Apparently the encoding needs to be specified in the filename like this when dealing with non-ASCII characters:
```
filename*=UTF-8''XXXXX
```
However, this is not supported by Axios. It also relies on the backend properly handling utf-8 encoding as well.
The lowest common …
=> Sanitise names of uploaded files or images

src/__tests__/components/fields/contact-field/contact-field.spec.tsx, src/components/fields/contact-field/utils.ts
**Changes**  
Enhance `getParsedPhoneNumber` function to parse phone numbers both with and without a space between the country code and national number.
**Background**  
Currently, the `getParsedPhoneNumber` function from FEE only accepts phone numbers that have a space between the country code and the national number (e.g., `+65 91234567`).
**Issue**  
When a default value is set for the contact field (e.g., `+6591234567` without a space), the function cannot parse this format into country code and national number, resulting in validation failures later in the flow.
**Expected Behavior**  
`getParsedPhoneNumber` should accept and correctly parse phone numbers both with and without a space after the country code (e.g., both `+65 91234567` and `+6591234567`).
**Additional Information**  
- …
=> [BOOKINGSG-7753][JEFF] enhance getParsedPhoneNumber function

package-lock.json, package.json
**Changes**
Update Axios from 1.7.9 to 1.11.0 due to medium vulnerabilities
https://security.snyk.io/package/npm/axios/1.7.9
-   Update Axios from 1.7.9 to 1.11.0 due to medium vulnerabilities
=> [MISC][WS] bump axios version

src/components/fields/location-field/location-modal/location-picker/location-picker.tsx, src/components/fields/location-field/location-modal/location-picker/types.ts, src/stories/3-fields/location-field/location-field.stories.tsx
**Changes**
Add `duration` to location field `mapPanZoom` prop. This allows us to control how long it takes for the map modal to zoom and center on a specified lat lng using the leaflet api
-   Add optional `duration` to location field `mapPanZoom` props
=> [MOL-19058][MA] Add zoom duration to location field props

src/components/fields/multi-select/multi-select.tsx, src/components/fields/nested-multi-select/nested-multi-select.tsx
**Changes**
Description of changes
- Replaced useDeepCompareEffect to useDeepCompareEffectNoCheck in MultiSelect and NestedMultiSelect component
- Add default options value to an empty array
-   Fix empty array options throw error when validating in MultiSelect and NestedMultiSelect component
-   You may refer to this [ticket](https://sgtechstack.atlassian.net/browse/BOOKINGSG-7967)
- Previously, when the options prop was empty, the validation inside useDeepCompareEffect failed, causing an error. By switching to useDeepCompareEffectNoCheck and ensuring options defaults to an empty array, the components can safely handle scenarios where the API fails or returns no data. This allows the process to continue without blocking the workflow, and …
=> [BOOKINGSG-7967][JEFF] fix empty array options throw error when submit

package-lock.json, package.json
**Changes**
- updated peer dependencies
- removed @floating-ui/dom as it's not actually needed for @floating-ui/react
- relaxed the version for @floating-ui/react to allow all minors, the caret doesn't work for 0.x version
-   Update `@floating-ui/react` peer dependency range to allow `>=0.26` minor versions and remove `@floating-ui/dom`
=> Relax Floating UI peer dependency
